// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.a2f_authoring.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.Services.A2FAuthoring.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.services.a2f_authoring.v1.proto</summary>
  public static partial class NvidiaAceServicesA2FAuthoringV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.services.a2f_authoring.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceServicesA2FAuthoringV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipudmlkaWFfYWNlLnNlcnZpY2VzLmEyZl9hdXRob3JpbmcudjEucHJvdG8S",
            "JG52aWRpYV9hY2Uuc2VydmljZXMuYTJmX2F1dGhvcmluZy52MRohbnZpZGlh",
            "X2FjZS5hMmZfYXV0aG9yaW5nLnYxLnByb3RvMvIBChNBMkZBdXRob3JpbmdT",
            "ZXJ2aWNlEmkKD1VwbG9hZEF1ZGlvQ2xpcBImLm52aWRpYV9hY2UuYTJmX2F1",
            "dGhvcmluZy52MS5BdWRpb0NsaXAaLC5udmlkaWFfYWNlLmEyZl9hdXRob3Jp",
            "bmcudjEuQXVkaW9DbGlwSGFuZGxlIgAScAoRR2V0QXZhdGFyRmFjZVBvc2US",
            "LC5udmlkaWFfYWNlLmEyZl9hdXRob3JpbmcudjEuRmFjZVBvc2VSZXF1ZXN0",
            "GisubnZpZGlhX2FjZS5hMmZfYXV0aG9yaW5nLnYxLkJsZW5kU2hhcGVEYXRh",
            "IgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NvidiaAce.A2FAuthoring.V1.NvidiaAceA2FAuthoringV1Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
