// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.a2f.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.Services.A2F.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.services.a2f.v1.proto</summary>
  public static partial class NvidiaAceServicesA2FV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.services.a2f.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceServicesA2FV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBudmlkaWFfYWNlLnNlcnZpY2VzLmEyZi52MS5wcm90bxIabnZpZGlhX2Fj",
            "ZS5zZXJ2aWNlcy5hMmYudjEaF252aWRpYV9hY2UuYTJmLnYxLnByb3RvGhpu",
            "dmlkaWFfYWNlLnN0YXR1cy52MS5wcm90bzJhCgpBMkZTZXJ2aWNlElMKD1B1",
            "c2hBdWRpb1N0cmVhbRIeLm52aWRpYV9hY2UuYTJmLnYxLkF1ZGlvU3RyZWFt",
            "GhwubnZpZGlhX2FjZS5zdGF0dXMudjEuU3RhdHVzIgAoAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NvidiaAce.A2F.V1.NvidiaAceA2FV1Reflection.Descriptor, global::NvidiaAce.Status.V1.NvidiaAceStatusV1Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
