// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.audio.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.Audio.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.audio.v1.proto</summary>
  public static partial class NvidiaAceAudioV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.audio.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceAudioV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChludmlkaWFfYWNlLmF1ZGlvLnYxLnByb3RvEhNudmlkaWFfYWNlLmF1ZGlv",
            "LnYxIsIBCgtBdWRpb0hlYWRlchJCCgxhdWRpb19mb3JtYXQYASABKA4yLC5u",
            "dmlkaWFfYWNlLmF1ZGlvLnYxLkF1ZGlvSGVhZGVyLkF1ZGlvRm9ybWF0EhUK",
            "DWNoYW5uZWxfY291bnQYAiABKA0SGgoSc2FtcGxlc19wZXJfc2Vjb25kGAMg",
            "ASgNEhcKD2JpdHNfcGVyX3NhbXBsZRgEIAEoDSIjCgtBdWRpb0Zvcm1hdBIU",
            "ChBBVURJT19GT1JNQVRfUENNEABiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Audio.V1.AudioHeader), global::NvidiaAce.Audio.V1.AudioHeader.Parser, new[]{ "AudioFormat", "ChannelCount", "SamplesPerSecond", "BitsPerSample" }, null, new[]{ typeof(global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AudioHeader : pb::IMessage<AudioHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioHeader> _parser = new pb::MessageParser<AudioHeader>(() => new AudioHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.Audio.V1.NvidiaAceAudioV1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioHeader(AudioHeader other) : this() {
      audioFormat_ = other.audioFormat_;
      channelCount_ = other.channelCount_;
      samplesPerSecond_ = other.samplesPerSecond_;
      bitsPerSample_ = other.bitsPerSample_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioHeader Clone() {
      return new AudioHeader(this);
    }

    /// <summary>Field number for the "audio_format" field.</summary>
    public const int AudioFormatFieldNumber = 1;
    private global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat audioFormat_ = global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat.Pcm;
    /// <summary>
    /// Example value: AUDIO_FORMAT_PCM
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat AudioFormat {
      get { return audioFormat_; }
      set {
        audioFormat_ = value;
      }
    }

    /// <summary>Field number for the "channel_count" field.</summary>
    public const int ChannelCountFieldNumber = 2;
    private uint channelCount_;
    /// <summary>
    /// Currently only mono sound must be supported.
    /// Example value: 1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChannelCount {
      get { return channelCount_; }
      set {
        channelCount_ = value;
      }
    }

    /// <summary>Field number for the "samples_per_second" field.</summary>
    public const int SamplesPerSecondFieldNumber = 3;
    private uint samplesPerSecond_;
    /// <summary>
    /// Defines the sample rate of the provided audio data
    /// Example value: 16000
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SamplesPerSecond {
      get { return samplesPerSecond_; }
      set {
        samplesPerSecond_ = value;
      }
    }

    /// <summary>Field number for the "bits_per_sample" field.</summary>
    public const int BitsPerSampleFieldNumber = 4;
    private uint bitsPerSample_;
    /// <summary>
    /// Currently only 16 bits per sample must be supported.
    /// Example value: 16
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BitsPerSample {
      get { return bitsPerSample_; }
      set {
        bitsPerSample_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AudioFormat != other.AudioFormat) return false;
      if (ChannelCount != other.ChannelCount) return false;
      if (SamplesPerSecond != other.SamplesPerSecond) return false;
      if (BitsPerSample != other.BitsPerSample) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AudioFormat != global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat.Pcm) hash ^= AudioFormat.GetHashCode();
      if (ChannelCount != 0) hash ^= ChannelCount.GetHashCode();
      if (SamplesPerSecond != 0) hash ^= SamplesPerSecond.GetHashCode();
      if (BitsPerSample != 0) hash ^= BitsPerSample.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AudioFormat != global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat.Pcm) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AudioFormat);
      }
      if (ChannelCount != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ChannelCount);
      }
      if (SamplesPerSecond != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(SamplesPerSecond);
      }
      if (BitsPerSample != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BitsPerSample);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AudioFormat != global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat.Pcm) {
        output.WriteRawTag(8);
        output.WriteEnum((int) AudioFormat);
      }
      if (ChannelCount != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ChannelCount);
      }
      if (SamplesPerSecond != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(SamplesPerSecond);
      }
      if (BitsPerSample != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BitsPerSample);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AudioFormat != global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat.Pcm) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AudioFormat);
      }
      if (ChannelCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChannelCount);
      }
      if (SamplesPerSecond != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SamplesPerSecond);
      }
      if (BitsPerSample != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BitsPerSample);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioHeader other) {
      if (other == null) {
        return;
      }
      if (other.AudioFormat != global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat.Pcm) {
        AudioFormat = other.AudioFormat;
      }
      if (other.ChannelCount != 0) {
        ChannelCount = other.ChannelCount;
      }
      if (other.SamplesPerSecond != 0) {
        SamplesPerSecond = other.SamplesPerSecond;
      }
      if (other.BitsPerSample != 0) {
        BitsPerSample = other.BitsPerSample;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AudioFormat = (global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat) input.ReadEnum();
            break;
          }
          case 16: {
            ChannelCount = input.ReadUInt32();
            break;
          }
          case 24: {
            SamplesPerSecond = input.ReadUInt32();
            break;
          }
          case 32: {
            BitsPerSample = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AudioFormat = (global::NvidiaAce.Audio.V1.AudioHeader.Types.AudioFormat) input.ReadEnum();
            break;
          }
          case 16: {
            ChannelCount = input.ReadUInt32();
            break;
          }
          case 24: {
            SamplesPerSecond = input.ReadUInt32();
            break;
          }
          case 32: {
            BitsPerSample = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AudioHeader message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum AudioFormat {
        [pbr::OriginalName("AUDIO_FORMAT_PCM")] Pcm = 0,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
