// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.animation_data.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.Services.AnimationData.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.services.animation_data.v1.proto</summary>
  public static partial class NvidiaAceServicesAnimationDataV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.services.animation_data.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceServicesAnimationDataV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitudmlkaWFfYWNlLnNlcnZpY2VzLmFuaW1hdGlvbl9kYXRhLnYxLnByb3Rv",
            "EiVudmlkaWFfYWNlLnNlcnZpY2VzLmFuaW1hdGlvbl9kYXRhLnYxGiJudmlk",
            "aWFfYWNlLmFuaW1hdGlvbl9kYXRhLnYxLnByb3RvGiBudmlkaWFfYWNlLmFu",
            "aW1hdGlvbl9pZC52MS5wcm90bxoabnZpZGlhX2FjZS5zdGF0dXMudjEucHJv",
            "dG8yggIKFEFuaW1hdGlvbkRhdGFTZXJ2aWNlEm4KF1B1c2hBbmltYXRpb25E",
            "YXRhU3RyZWFtEjEubnZpZGlhX2FjZS5hbmltYXRpb25fZGF0YS52MS5Bbmlt",
            "YXRpb25EYXRhU3RyZWFtGhwubnZpZGlhX2FjZS5zdGF0dXMudjEuU3RhdHVz",
            "IgAoARJ6ChdQdWxsQW5pbWF0aW9uRGF0YVN0cmVhbRIoLm52aWRpYV9hY2Uu",
            "YW5pbWF0aW9uX2lkLnYxLkFuaW1hdGlvbklkcxoxLm52aWRpYV9hY2UuYW5p",
            "bWF0aW9uX2RhdGEudjEuQW5pbWF0aW9uRGF0YVN0cmVhbSIAMAFiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NvidiaAce.AnimationData.V1.NvidiaAceAnimationDataV1Reflection.Descriptor, global::NvidiaAce.AnimationId.V1.NvidiaAceAnimationIdV1Reflection.Descriptor, global::NvidiaAce.Status.V1.NvidiaAceStatusV1Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
