// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.animation_data.v1.proto
// </auto-generated>
// Original file comments:
//
// SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NvidiaAce.Services.AnimationData.V1 {
  /// <summary>
  /// 2 RPC exist to provide a stream of animation data
  /// The RPC to implement depends on if the part of the service
  /// is a client or a server.
  /// E.g.: In the case of Animation Graph Microservice, we implement both RPCs.
  /// One to receive and one to send.
  /// </summary>
  public static partial class AnimationDataService
  {
    static readonly string __ServiceName = "nvidia_ace.services.animation_data.v1.AnimationDataService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.AnimationData.V1.AnimationDataStream> __Marshaller_nvidia_ace_animation_data_v1_AnimationDataStream = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.AnimationData.V1.AnimationDataStream.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.Status.V1.Status> __Marshaller_nvidia_ace_status_v1_Status = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.Status.V1.Status.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.AnimationId.V1.AnimationIds> __Marshaller_nvidia_ace_animation_id_v1_AnimationIds = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.AnimationId.V1.AnimationIds.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::NvidiaAce.AnimationData.V1.AnimationDataStream, global::NvidiaAce.Status.V1.Status> __Method_PushAnimationDataStream = new grpc::Method<global::NvidiaAce.AnimationData.V1.AnimationDataStream, global::NvidiaAce.Status.V1.Status>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "PushAnimationDataStream",
        __Marshaller_nvidia_ace_animation_data_v1_AnimationDataStream,
        __Marshaller_nvidia_ace_status_v1_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::NvidiaAce.AnimationId.V1.AnimationIds, global::NvidiaAce.AnimationData.V1.AnimationDataStream> __Method_PullAnimationDataStream = new grpc::Method<global::NvidiaAce.AnimationId.V1.AnimationIds, global::NvidiaAce.AnimationData.V1.AnimationDataStream>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "PullAnimationDataStream",
        __Marshaller_nvidia_ace_animation_id_v1_AnimationIds,
        __Marshaller_nvidia_ace_animation_data_v1_AnimationDataStream);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NvidiaAce.Services.AnimationData.V1.NvidiaAceServicesAnimationDataV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AnimationDataService</summary>
    [grpc::BindServiceMethod(typeof(AnimationDataService), "BindService")]
    public abstract partial class AnimationDataServiceBase
    {
      /// <summary>
      /// When the service creating the animation data is a client from the service receiving them
      /// This push RPC must be used.
      /// An example for that is Audio2Face Microservice creating animation data and sending them
      /// to Animation Graph Microservice
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::NvidiaAce.Status.V1.Status> PushAnimationDataStream(grpc::IAsyncStreamReader<global::NvidiaAce.AnimationData.V1.AnimationDataStream> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// When the service creating the animation data is a server from the service receiving them
      /// This pull RPC must be used.
      /// An example for that is the Omniverse Renderer Microservice requesting animation data to the
      /// Animation Graph Microservice.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task PullAnimationDataStream(global::NvidiaAce.AnimationId.V1.AnimationIds request, grpc::IServerStreamWriter<global::NvidiaAce.AnimationData.V1.AnimationDataStream> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AnimationDataService</summary>
    public partial class AnimationDataServiceClient : grpc::ClientBase<AnimationDataServiceClient>
    {
      /// <summary>Creates a new client for AnimationDataService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AnimationDataServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AnimationDataService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AnimationDataServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AnimationDataServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AnimationDataServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// When the service creating the animation data is a client from the service receiving them
      /// This push RPC must be used.
      /// An example for that is Audio2Face Microservice creating animation data and sending them
      /// to Animation Graph Microservice
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::NvidiaAce.AnimationData.V1.AnimationDataStream, global::NvidiaAce.Status.V1.Status> PushAnimationDataStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PushAnimationDataStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// When the service creating the animation data is a client from the service receiving them
      /// This push RPC must be used.
      /// An example for that is Audio2Face Microservice creating animation data and sending them
      /// to Animation Graph Microservice
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::NvidiaAce.AnimationData.V1.AnimationDataStream, global::NvidiaAce.Status.V1.Status> PushAnimationDataStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_PushAnimationDataStream, null, options);
      }
      /// <summary>
      /// When the service creating the animation data is a server from the service receiving them
      /// This pull RPC must be used.
      /// An example for that is the Omniverse Renderer Microservice requesting animation data to the
      /// Animation Graph Microservice.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::NvidiaAce.AnimationData.V1.AnimationDataStream> PullAnimationDataStream(global::NvidiaAce.AnimationId.V1.AnimationIds request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PullAnimationDataStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// When the service creating the animation data is a server from the service receiving them
      /// This pull RPC must be used.
      /// An example for that is the Omniverse Renderer Microservice requesting animation data to the
      /// Animation Graph Microservice.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::NvidiaAce.AnimationData.V1.AnimationDataStream> PullAnimationDataStream(global::NvidiaAce.AnimationId.V1.AnimationIds request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_PullAnimationDataStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AnimationDataServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AnimationDataServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AnimationDataServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PushAnimationDataStream, serviceImpl.PushAnimationDataStream)
          .AddMethod(__Method_PullAnimationDataStream, serviceImpl.PullAnimationDataStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AnimationDataServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PushAnimationDataStream, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::NvidiaAce.AnimationData.V1.AnimationDataStream, global::NvidiaAce.Status.V1.Status>(serviceImpl.PushAnimationDataStream));
      serviceBinder.AddMethod(__Method_PullAnimationDataStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::NvidiaAce.AnimationId.V1.AnimationIds, global::NvidiaAce.AnimationData.V1.AnimationDataStream>(serviceImpl.PullAnimationDataStream));
    }

  }
}
#endregion
