// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.a2f_authoring.v1.proto
// </auto-generated>
// Original file comments:
// Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NvidiaAce.Services.A2FAuthoring.V1 {
  /// <summary>
  /// This API allows to get unique frames from Audio2Face inference (also known as authoring)
  /// </summary>
  public static partial class A2FAuthoringService
  {
    static readonly string __ServiceName = "nvidia_ace.services.a2f_authoring.v1.A2FAuthoringService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.A2FAuthoring.V1.AudioClip> __Marshaller_nvidia_ace_a2f_authoring_v1_AudioClip = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.A2FAuthoring.V1.AudioClip.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle> __Marshaller_nvidia_ace_a2f_authoring_v1_AudioClipHandle = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest> __Marshaller_nvidia_ace_a2f_authoring_v1_FacePoseRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.A2FAuthoring.V1.BlendShapeData> __Marshaller_nvidia_ace_a2f_authoring_v1_BlendShapeData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.A2FAuthoring.V1.BlendShapeData.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::NvidiaAce.A2FAuthoring.V1.AudioClip, global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle> __Method_UploadAudioClip = new grpc::Method<global::NvidiaAce.A2FAuthoring.V1.AudioClip, global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UploadAudioClip",
        __Marshaller_nvidia_ace_a2f_authoring_v1_AudioClip,
        __Marshaller_nvidia_ace_a2f_authoring_v1_AudioClipHandle);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest, global::NvidiaAce.A2FAuthoring.V1.BlendShapeData> __Method_GetAvatarFacePose = new grpc::Method<global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest, global::NvidiaAce.A2FAuthoring.V1.BlendShapeData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAvatarFacePose",
        __Marshaller_nvidia_ace_a2f_authoring_v1_FacePoseRequest,
        __Marshaller_nvidia_ace_a2f_authoring_v1_BlendShapeData);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NvidiaAce.Services.A2FAuthoring.V1.NvidiaAceServicesA2FAuthoringV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of A2FAuthoringService</summary>
    [grpc::BindServiceMethod(typeof(A2FAuthoringService), "BindService")]
    public abstract partial class A2FAuthoringServiceBase
    {
      /// <summary>
      /// Upload the audio clip to the AuthoringService to be processed.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle> UploadAudioClip(global::NvidiaAce.A2FAuthoring.V1.AudioClip request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Request a single animation frame at the specified timecode.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::NvidiaAce.A2FAuthoring.V1.BlendShapeData> GetAvatarFacePose(global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for A2FAuthoringService</summary>
    public partial class A2FAuthoringServiceClient : grpc::ClientBase<A2FAuthoringServiceClient>
    {
      /// <summary>Creates a new client for A2FAuthoringService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public A2FAuthoringServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for A2FAuthoringService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public A2FAuthoringServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected A2FAuthoringServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected A2FAuthoringServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Upload the audio clip to the AuthoringService to be processed.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle UploadAudioClip(global::NvidiaAce.A2FAuthoring.V1.AudioClip request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadAudioClip(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Upload the audio clip to the AuthoringService to be processed.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle UploadAudioClip(global::NvidiaAce.A2FAuthoring.V1.AudioClip request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UploadAudioClip, null, options, request);
      }
      /// <summary>
      /// Upload the audio clip to the AuthoringService to be processed.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle> UploadAudioClipAsync(global::NvidiaAce.A2FAuthoring.V1.AudioClip request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UploadAudioClipAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Upload the audio clip to the AuthoringService to be processed.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle> UploadAudioClipAsync(global::NvidiaAce.A2FAuthoring.V1.AudioClip request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UploadAudioClip, null, options, request);
      }
      /// <summary>
      /// Request a single animation frame at the specified timecode.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::NvidiaAce.A2FAuthoring.V1.BlendShapeData GetAvatarFacePose(global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAvatarFacePose(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Request a single animation frame at the specified timecode.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::NvidiaAce.A2FAuthoring.V1.BlendShapeData GetAvatarFacePose(global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAvatarFacePose, null, options, request);
      }
      /// <summary>
      /// Request a single animation frame at the specified timecode.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::NvidiaAce.A2FAuthoring.V1.BlendShapeData> GetAvatarFacePoseAsync(global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAvatarFacePoseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Request a single animation frame at the specified timecode.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::NvidiaAce.A2FAuthoring.V1.BlendShapeData> GetAvatarFacePoseAsync(global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAvatarFacePose, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override A2FAuthoringServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new A2FAuthoringServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(A2FAuthoringServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_UploadAudioClip, serviceImpl.UploadAudioClip)
          .AddMethod(__Method_GetAvatarFacePose, serviceImpl.GetAvatarFacePose).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, A2FAuthoringServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_UploadAudioClip, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::NvidiaAce.A2FAuthoring.V1.AudioClip, global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle>(serviceImpl.UploadAudioClip));
      serviceBinder.AddMethod(__Method_GetAvatarFacePose, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest, global::NvidiaAce.A2FAuthoring.V1.BlendShapeData>(serviceImpl.GetAvatarFacePose));
    }

  }
}
#endregion
