// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.emotion_with_timecode.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.EmotionWithTimecode.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.emotion_with_timecode.v1.proto</summary>
  public static partial class NvidiaAceEmotionWithTimecodeV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.emotion_with_timecode.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceEmotionWithTimecodeV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiludmlkaWFfYWNlLmVtb3Rpb25fd2l0aF90aW1lY29kZS52MS5wcm90bxIj",
            "bnZpZGlhX2FjZS5lbW90aW9uX3dpdGhfdGltZWNvZGUudjEisAEKE0Vtb3Rp",
            "b25XaXRoVGltZUNvZGUSEQoJdGltZV9jb2RlGAEgASgBElYKB2Vtb3Rpb24Y",
            "AiADKAsyRS5udmlkaWFfYWNlLmVtb3Rpb25fd2l0aF90aW1lY29kZS52MS5F",
            "bW90aW9uV2l0aFRpbWVDb2RlLkVtb3Rpb25FbnRyeRouCgxFbW90aW9uRW50",
            "cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgCOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode), global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode.Parser, new[]{ "TimeCode", "Emotion" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Emotions with time code allow clients to control when emotions are
  /// being applied to an audio clip
  /// Example 1:
  /// time_code = 0.0
  /// emotion = { "joy" : 1.0 }
  /// At the start of the audio clip, the joy emotion will be applied
  /// at its maximum intensity.
  /// Example 2:
  /// time_code = 3.0
  /// emotion = { "outofbreath" : 0.5 }
  /// At the 3-second mark in the audio clip, the outofbreath emotion
  /// will be applied at half intensity.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EmotionWithTimeCode : pb::IMessage<EmotionWithTimeCode>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EmotionWithTimeCode> _parser = new pb::MessageParser<EmotionWithTimeCode>(() => new EmotionWithTimeCode());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EmotionWithTimeCode> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.EmotionWithTimecode.V1.NvidiaAceEmotionWithTimecodeV1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmotionWithTimeCode() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmotionWithTimeCode(EmotionWithTimeCode other) : this() {
      timeCode_ = other.timeCode_;
      emotion_ = other.emotion_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmotionWithTimeCode Clone() {
      return new EmotionWithTimeCode(this);
    }

    /// <summary>Field number for the "time_code" field.</summary>
    public const int TimeCodeFieldNumber = 1;
    private double timeCode_;
    /// <summary>
    /// Time when to apply the selected emotion
    /// This time is relative to the beginning of the audio clip
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TimeCode {
      get { return timeCode_; }
      set {
        timeCode_ = value;
      }
    }

    /// <summary>Field number for the "emotion" field.</summary>
    public const int EmotionFieldNumber = 2;
    private static readonly pbc::MapField<string, float>.Codec _map_emotion_codec
        = new pbc::MapField<string, float>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForFloat(21, 0F), 18);
    private readonly pbc::MapField<string, float> emotion_ = new pbc::MapField<string, float>();
    /// <summary>
    /// This maps the emotion names to the corresponding emotion strength
    /// Missing emotion values will be set to 0.0
    /// The following emotions can be set:
    /// "amazement", "anger", "cheekiness", "disgust", "fear",
    /// "grief", "joy", "outofbreath", "pain", "sadness"
    /// Emotion values must be set between 0.0 and 1.0
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, float> Emotion {
      get { return emotion_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EmotionWithTimeCode);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EmotionWithTimeCode other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TimeCode, other.TimeCode)) return false;
      if (!Emotion.Equals(other.Emotion)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TimeCode != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TimeCode);
      hash ^= Emotion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TimeCode != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TimeCode);
      }
      emotion_.WriteTo(output, _map_emotion_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TimeCode != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(TimeCode);
      }
      emotion_.WriteTo(ref output, _map_emotion_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TimeCode != 0D) {
        size += 1 + 8;
      }
      size += emotion_.CalculateSize(_map_emotion_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EmotionWithTimeCode other) {
      if (other == null) {
        return;
      }
      if (other.TimeCode != 0D) {
        TimeCode = other.TimeCode;
      }
      emotion_.MergeFrom(other.emotion_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            TimeCode = input.ReadDouble();
            break;
          }
          case 18: {
            emotion_.AddEntriesFrom(input, _map_emotion_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 9: {
            TimeCode = input.ReadDouble();
            break;
          }
          case 18: {
            emotion_.AddEntriesFrom(ref input, _map_emotion_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
