// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.a2x_export_config.v1.proto
// </auto-generated>
// Original file comments:
//
// SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NvidiaAce.Services.A2XExportConfig.V1 {
  public static partial class A2XExportConfigService
  {
    static readonly string __ServiceName = "nvidia_ace.services.a2x_export_config.v1.A2XExportConfigService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.Services.A2XExportConfig.V1.ConfigsTypeRequest> __Marshaller_nvidia_ace_services_a2x_export_config_v1_ConfigsTypeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.Services.A2XExportConfig.V1.ConfigsTypeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.Services.A2XExportConfig.V1.A2XConfig> __Marshaller_nvidia_ace_services_a2x_export_config_v1_A2XConfig = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.Services.A2XExportConfig.V1.A2XConfig.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::NvidiaAce.Services.A2XExportConfig.V1.ConfigsTypeRequest, global::NvidiaAce.Services.A2XExportConfig.V1.A2XConfig> __Method_GetConfigs = new grpc::Method<global::NvidiaAce.Services.A2XExportConfig.V1.ConfigsTypeRequest, global::NvidiaAce.Services.A2XExportConfig.V1.A2XConfig>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetConfigs",
        __Marshaller_nvidia_ace_services_a2x_export_config_v1_ConfigsTypeRequest,
        __Marshaller_nvidia_ace_services_a2x_export_config_v1_A2XConfig);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NvidiaAce.Services.A2XExportConfig.V1.NvidiaAceServicesA2XExportConfigV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of A2XExportConfigService</summary>
    [grpc::BindServiceMethod(typeof(A2XExportConfigService), "BindService")]
    public abstract partial class A2XExportConfigServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetConfigs(global::NvidiaAce.Services.A2XExportConfig.V1.ConfigsTypeRequest request, grpc::IServerStreamWriter<global::NvidiaAce.Services.A2XExportConfig.V1.A2XConfig> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for A2XExportConfigService</summary>
    public partial class A2XExportConfigServiceClient : grpc::ClientBase<A2XExportConfigServiceClient>
    {
      /// <summary>Creates a new client for A2XExportConfigService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public A2XExportConfigServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for A2XExportConfigService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public A2XExportConfigServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected A2XExportConfigServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected A2XExportConfigServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::NvidiaAce.Services.A2XExportConfig.V1.A2XConfig> GetConfigs(global::NvidiaAce.Services.A2XExportConfig.V1.ConfigsTypeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetConfigs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::NvidiaAce.Services.A2XExportConfig.V1.A2XConfig> GetConfigs(global::NvidiaAce.Services.A2XExportConfig.V1.ConfigsTypeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetConfigs, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override A2XExportConfigServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new A2XExportConfigServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(A2XExportConfigServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetConfigs, serviceImpl.GetConfigs).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, A2XExportConfigServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetConfigs, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::NvidiaAce.Services.A2XExportConfig.V1.ConfigsTypeRequest, global::NvidiaAce.Services.A2XExportConfig.V1.A2XConfig>(serviceImpl.GetConfigs));
    }

  }
}
#endregion
