// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.animation_controller.v1.proto
// </auto-generated>
// Original file comments:
//
// SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NvidiaAce.Services.AnimationController.V1 {
  public static partial class AnimationControllerService
  {
    static readonly string __ServiceName = "nvidia_ace.services.animation_controller.v1.AnimationControllerService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus> __Marshaller_nvidia_ace_services_animation_controller_v1_AnimationIdsOrStatus = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.AnimationId.V1.AnimationIds> __Marshaller_nvidia_ace_animation_id_v1_AnimationIds = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.AnimationId.V1.AnimationIds.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.AnimationData.V1.AnimationDataStream> __Marshaller_nvidia_ace_animation_data_v1_AnimationDataStream = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.AnimationData.V1.AnimationDataStream.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.A2F.V1.AudioStream> __Marshaller_nvidia_ace_a2f_v1_AudioStream = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.A2F.V1.AudioStream.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.Status.V1.Status> __Marshaller_nvidia_ace_status_v1_Status = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.Status.V1.Status.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest> __Marshaller_nvidia_ace_services_animation_controller_v1_AnimationGraphRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus> __Method_RequestAnimationIds = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RequestAnimationIds",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_nvidia_ace_services_animation_controller_v1_AnimationIdsOrStatus);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::NvidiaAce.AnimationId.V1.AnimationIds, global::NvidiaAce.AnimationData.V1.AnimationDataStream> __Method_PullAnimationDataStream = new grpc::Method<global::NvidiaAce.AnimationId.V1.AnimationIds, global::NvidiaAce.AnimationData.V1.AnimationDataStream>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "PullAnimationDataStream",
        __Marshaller_nvidia_ace_animation_id_v1_AnimationIds,
        __Marshaller_nvidia_ace_animation_data_v1_AnimationDataStream);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::NvidiaAce.A2F.V1.AudioStream, global::NvidiaAce.Status.V1.Status> __Method_PushAudioStream = new grpc::Method<global::NvidiaAce.A2F.V1.AudioStream, global::NvidiaAce.Status.V1.Status>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "PushAudioStream",
        __Marshaller_nvidia_ace_a2f_v1_AudioStream,
        __Marshaller_nvidia_ace_status_v1_Status);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest, global::NvidiaAce.Status.V1.Status> __Method_UpdateAnimationGraphVariable = new grpc::Method<global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest, global::NvidiaAce.Status.V1.Status>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "UpdateAnimationGraphVariable",
        __Marshaller_nvidia_ace_services_animation_controller_v1_AnimationGraphRequest,
        __Marshaller_nvidia_ace_status_v1_Status);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NvidiaAce.Services.AnimationController.V1.NvidiaAceServicesAnimationControllerV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AnimationControllerService</summary>
    [grpc::BindServiceMethod(typeof(AnimationControllerService), "BindService")]
    public abstract partial class AnimationControllerServiceBase
    {
      /// <summary>
      /// First request an ID to communicate with the service.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus> RequestAnimationIds(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Then start pulling animation data.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task PullAnimationDataStream(global::NvidiaAce.AnimationId.V1.AnimationIds request, grpc::IServerStreamWriter<global::NvidiaAce.AnimationData.V1.AnimationDataStream> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Send audio data as needed.
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::NvidiaAce.Status.V1.Status> PushAudioStream(grpc::IAsyncStreamReader<global::NvidiaAce.A2F.V1.AudioStream> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Update animation graph variables as needed.
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::NvidiaAce.Status.V1.Status> UpdateAnimationGraphVariable(grpc::IAsyncStreamReader<global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AnimationControllerService</summary>
    public partial class AnimationControllerServiceClient : grpc::ClientBase<AnimationControllerServiceClient>
    {
      /// <summary>Creates a new client for AnimationControllerService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AnimationControllerServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AnimationControllerService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AnimationControllerServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AnimationControllerServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AnimationControllerServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// First request an ID to communicate with the service.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus RequestAnimationIds(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RequestAnimationIds(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// First request an ID to communicate with the service.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus RequestAnimationIds(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RequestAnimationIds, null, options, request);
      }
      /// <summary>
      /// First request an ID to communicate with the service.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus> RequestAnimationIdsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RequestAnimationIdsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// First request an ID to communicate with the service.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus> RequestAnimationIdsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RequestAnimationIds, null, options, request);
      }
      /// <summary>
      /// Then start pulling animation data.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::NvidiaAce.AnimationData.V1.AnimationDataStream> PullAnimationDataStream(global::NvidiaAce.AnimationId.V1.AnimationIds request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PullAnimationDataStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Then start pulling animation data.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::NvidiaAce.AnimationData.V1.AnimationDataStream> PullAnimationDataStream(global::NvidiaAce.AnimationId.V1.AnimationIds request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_PullAnimationDataStream, null, options, request);
      }
      /// <summary>
      /// Send audio data as needed.
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::NvidiaAce.A2F.V1.AudioStream, global::NvidiaAce.Status.V1.Status> PushAudioStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PushAudioStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Send audio data as needed.
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::NvidiaAce.A2F.V1.AudioStream, global::NvidiaAce.Status.V1.Status> PushAudioStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_PushAudioStream, null, options);
      }
      /// <summary>
      /// Update animation graph variables as needed.
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest, global::NvidiaAce.Status.V1.Status> UpdateAnimationGraphVariable(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAnimationGraphVariable(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Update animation graph variables as needed.
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest, global::NvidiaAce.Status.V1.Status> UpdateAnimationGraphVariable(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_UpdateAnimationGraphVariable, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AnimationControllerServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AnimationControllerServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AnimationControllerServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RequestAnimationIds, serviceImpl.RequestAnimationIds)
          .AddMethod(__Method_PullAnimationDataStream, serviceImpl.PullAnimationDataStream)
          .AddMethod(__Method_PushAudioStream, serviceImpl.PushAudioStream)
          .AddMethod(__Method_UpdateAnimationGraphVariable, serviceImpl.UpdateAnimationGraphVariable).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AnimationControllerServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RequestAnimationIds, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus>(serviceImpl.RequestAnimationIds));
      serviceBinder.AddMethod(__Method_PullAnimationDataStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::NvidiaAce.AnimationId.V1.AnimationIds, global::NvidiaAce.AnimationData.V1.AnimationDataStream>(serviceImpl.PullAnimationDataStream));
      serviceBinder.AddMethod(__Method_PushAudioStream, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::NvidiaAce.A2F.V1.AudioStream, global::NvidiaAce.Status.V1.Status>(serviceImpl.PushAudioStream));
      serviceBinder.AddMethod(__Method_UpdateAnimationGraphVariable, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest, global::NvidiaAce.Status.V1.Status>(serviceImpl.UpdateAnimationGraphVariable));
    }

  }
}
#endregion
