// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.a2f_controller.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.Services.A2FController.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.services.a2f_controller.v1.proto</summary>
  public static partial class NvidiaAceServicesA2FControllerV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.services.a2f_controller.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceServicesA2FControllerV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitudmlkaWFfYWNlLnNlcnZpY2VzLmEyZl9jb250cm9sbGVyLnYxLnByb3Rv",
            "EiVudmlkaWFfYWNlLnNlcnZpY2VzLmEyZl9jb250cm9sbGVyLnYxGh5udmlk",
            "aWFfYWNlLmNvbnRyb2xsZXIudjEucHJvdG8aIG52aWRpYV9hY2UuYW5pbWF0",
            "aW9uX2lkLnYxLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8y",
            "iAEKFEEyRkNvbnRyb2xsZXJTZXJ2aWNlEnAKElByb2Nlc3NBdWRpb1N0cmVh",
            "bRIlLm52aWRpYV9hY2UuY29udHJvbGxlci52MS5BdWRpb1N0cmVhbRotLm52",
            "aWRpYV9hY2UuY29udHJvbGxlci52MS5BbmltYXRpb25EYXRhU3RyZWFtIgAo",
            "ATABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NvidiaAce.Controller.V1.NvidiaAceControllerV1Reflection.Descriptor, global::NvidiaAce.AnimationId.V1.NvidiaAceAnimationIdV1Reflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
