// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.emotion_aggregate.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.EmotionAggregate.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.emotion_aggregate.v1.proto</summary>
  public static partial class NvidiaAceEmotionAggregateV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.emotion_aggregate.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceEmotionAggregateV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVudmlkaWFfYWNlLmVtb3Rpb25fYWdncmVnYXRlLnYxLnByb3RvEh9udmlk",
            "aWFfYWNlLmVtb3Rpb25fYWdncmVnYXRlLnYxGiludmlkaWFfYWNlLmVtb3Rp",
            "b25fd2l0aF90aW1lY29kZS52MS5wcm90byKJAgoQRW1vdGlvbkFnZ3JlZ2F0",
            "ZRJQCg5pbnB1dF9lbW90aW9ucxgBIAMoCzI4Lm52aWRpYV9hY2UuZW1vdGlv",
            "bl93aXRoX3RpbWVjb2RlLnYxLkVtb3Rpb25XaXRoVGltZUNvZGUSTAoKYTJl",
            "X291dHB1dBgCIAMoCzI4Lm52aWRpYV9hY2UuZW1vdGlvbl93aXRoX3RpbWVj",
            "b2RlLnYxLkVtb3Rpb25XaXRoVGltZUNvZGUSVQoTYTJmX3Ntb290aGVkX291",
            "dHB1dBgDIAMoCzI4Lm52aWRpYV9hY2UuZW1vdGlvbl93aXRoX3RpbWVjb2Rl",
            "LnYxLkVtb3Rpb25XaXRoVGltZUNvZGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NvidiaAce.EmotionWithTimecode.V1.NvidiaAceEmotionWithTimecodeV1Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.EmotionAggregate.V1.EmotionAggregate), global::NvidiaAce.EmotionAggregate.V1.EmotionAggregate.Parser, new[]{ "InputEmotions", "A2EOutput", "A2FSmoothedOutput" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// WARNING: alpha version of the emotion output of Audio2Face Microservice
  /// This can be subject to change.
  /// The primary function of this message is to enable the analysis of blendshape
  /// data associated with the emotion data.
  /// See the documentation and the provided sample application for more information
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EmotionAggregate : pb::IMessage<EmotionAggregate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EmotionAggregate> _parser = new pb::MessageParser<EmotionAggregate>(() => new EmotionAggregate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EmotionAggregate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.EmotionAggregate.V1.NvidiaAceEmotionAggregateV1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmotionAggregate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmotionAggregate(EmotionAggregate other) : this() {
      inputEmotions_ = other.inputEmotions_.Clone();
      a2EOutput_ = other.a2EOutput_.Clone();
      a2FSmoothedOutput_ = other.a2FSmoothedOutput_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EmotionAggregate Clone() {
      return new EmotionAggregate(this);
    }

    /// <summary>Field number for the "input_emotions" field.</summary>
    public const int InputEmotionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> _repeated_inputEmotions_codec
        = pb::FieldCodec.ForMessage(10, global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode.Parser);
    private readonly pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> inputEmotions_ = new pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode>();
    /// <summary>
    /// Input emotions refer to the emotions provided by the user of the Audio2Face
    /// Service before any processing is applied.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> InputEmotions {
      get { return inputEmotions_; }
    }

    /// <summary>Field number for the "a2e_output" field.</summary>
    public const int A2EOutputFieldNumber = 2;
    private static readonly pb::FieldCodec<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> _repeated_a2EOutput_codec
        = pb::FieldCodec.ForMessage(18, global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode.Parser);
    private readonly pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> a2EOutput_ = new pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode>();
    /// <summary>
    /// These emotions are a blend between:
    /// 1. emotions generated by the Audio2Emotion model
    /// 2. input_emotions
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> A2EOutput {
      get { return a2EOutput_; }
    }

    /// <summary>Field number for the "a2f_smoothed_output" field.</summary>
    public const int A2FSmoothedOutputFieldNumber = 3;
    private static readonly pb::FieldCodec<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> _repeated_a2FSmoothedOutput_codec
        = pb::FieldCodec.ForMessage(26, global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode.Parser);
    private readonly pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> a2FSmoothedOutput_ = new pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode>();
    /// <summary>
    /// These emotions are the emotions coming from a2e_output smoothed over time
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::NvidiaAce.EmotionWithTimecode.V1.EmotionWithTimeCode> A2FSmoothedOutput {
      get { return a2FSmoothedOutput_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as EmotionAggregate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EmotionAggregate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!inputEmotions_.Equals(other.inputEmotions_)) return false;
      if(!a2EOutput_.Equals(other.a2EOutput_)) return false;
      if(!a2FSmoothedOutput_.Equals(other.a2FSmoothedOutput_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= inputEmotions_.GetHashCode();
      hash ^= a2EOutput_.GetHashCode();
      hash ^= a2FSmoothedOutput_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      inputEmotions_.WriteTo(output, _repeated_inputEmotions_codec);
      a2EOutput_.WriteTo(output, _repeated_a2EOutput_codec);
      a2FSmoothedOutput_.WriteTo(output, _repeated_a2FSmoothedOutput_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      inputEmotions_.WriteTo(ref output, _repeated_inputEmotions_codec);
      a2EOutput_.WriteTo(ref output, _repeated_a2EOutput_codec);
      a2FSmoothedOutput_.WriteTo(ref output, _repeated_a2FSmoothedOutput_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += inputEmotions_.CalculateSize(_repeated_inputEmotions_codec);
      size += a2EOutput_.CalculateSize(_repeated_a2EOutput_codec);
      size += a2FSmoothedOutput_.CalculateSize(_repeated_a2FSmoothedOutput_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EmotionAggregate other) {
      if (other == null) {
        return;
      }
      inputEmotions_.Add(other.inputEmotions_);
      a2EOutput_.Add(other.a2EOutput_);
      a2FSmoothedOutput_.Add(other.a2FSmoothedOutput_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            inputEmotions_.AddEntriesFrom(input, _repeated_inputEmotions_codec);
            break;
          }
          case 18: {
            a2EOutput_.AddEntriesFrom(input, _repeated_a2EOutput_codec);
            break;
          }
          case 26: {
            a2FSmoothedOutput_.AddEntriesFrom(input, _repeated_a2FSmoothedOutput_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            inputEmotions_.AddEntriesFrom(ref input, _repeated_inputEmotions_codec);
            break;
          }
          case 18: {
            a2EOutput_.AddEntriesFrom(ref input, _repeated_a2EOutput_codec);
            break;
          }
          case 26: {
            a2FSmoothedOutput_.AddEntriesFrom(ref input, _repeated_a2FSmoothedOutput_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
