// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.services.animation_controller.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.Services.AnimationController.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.services.animation_controller.v1.proto</summary>
  public static partial class NvidiaAceServicesAnimationControllerV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.services.animation_controller.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceServicesAnimationControllerV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFudmlkaWFfYWNlLnNlcnZpY2VzLmFuaW1hdGlvbl9jb250cm9sbGVyLnYx",
            "LnByb3RvEitudmlkaWFfYWNlLnNlcnZpY2VzLmFuaW1hdGlvbl9jb250cm9s",
            "bGVyLnYxGh5udmlkaWFfYWNlLmNvbnRyb2xsZXIudjEucHJvdG8aGm52aWRp",
            "YV9hY2Uuc3RhdHVzLnYxLnByb3RvGiBudmlkaWFfYWNlLmFuaW1hdGlvbl9p",
            "ZC52MS5wcm90bxoibnZpZGlhX2FjZS5hbmltYXRpb25fZGF0YS52MS5wcm90",
            "bxoXbnZpZGlhX2FjZS5hMmYudjEucHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9l",
            "bXB0eS5wcm90byKnAQoVQW5pbWF0aW9uR3JhcGhSZXF1ZXN0Ej8KDWFuaW1h",
            "dGlvbl9pZHMYASABKAsyKC5udmlkaWFfYWNlLmFuaW1hdGlvbl9pZC52MS5B",
            "bmltYXRpb25JZHMSJQodYW5pbWF0aW9uX2dyYXBoX3ZhcmlhYmxlX25hbWUY",
            "AiABKAkSJgoeYW5pbWF0aW9uX2dyYXBoX3ZhcmlhYmxlX3ZhbHVlGAMgASgJ",
            "IpUBChRBbmltYXRpb25JZHNPclN0YXR1cxJBCg1hbmltYXRpb25faWRzGAEg",
            "ASgLMigubnZpZGlhX2FjZS5hbmltYXRpb25faWQudjEuQW5pbWF0aW9uSWRz",
            "SAASLgoGc3RhdHVzGAIgASgLMhwubnZpZGlhX2FjZS5zdGF0dXMudjEuU3Rh",
            "dHVzSABCCgoIcmVzcG9uc2Uy6AMKGkFuaW1hdGlvbkNvbnRyb2xsZXJTZXJ2",
            "aWNlEnIKE1JlcXVlc3RBbmltYXRpb25JZHMSFi5nb29nbGUucHJvdG9idWYu",
            "RW1wdHkaQS5udmlkaWFfYWNlLnNlcnZpY2VzLmFuaW1hdGlvbl9jb250cm9s",
            "bGVyLnYxLkFuaW1hdGlvbklkc09yU3RhdHVzIgASegoXUHVsbEFuaW1hdGlv",
            "bkRhdGFTdHJlYW0SKC5udmlkaWFfYWNlLmFuaW1hdGlvbl9pZC52MS5Bbmlt",
            "YXRpb25JZHMaMS5udmlkaWFfYWNlLmFuaW1hdGlvbl9kYXRhLnYxLkFuaW1h",
            "dGlvbkRhdGFTdHJlYW0iADABElMKD1B1c2hBdWRpb1N0cmVhbRIeLm52aWRp",
            "YV9hY2UuYTJmLnYxLkF1ZGlvU3RyZWFtGhwubnZpZGlhX2FjZS5zdGF0dXMu",
            "djEuU3RhdHVzIgAoARKEAQocVXBkYXRlQW5pbWF0aW9uR3JhcGhWYXJpYWJs",
            "ZRJCLm52aWRpYV9hY2Uuc2VydmljZXMuYW5pbWF0aW9uX2NvbnRyb2xsZXIu",
            "djEuQW5pbWF0aW9uR3JhcGhSZXF1ZXN0GhwubnZpZGlhX2FjZS5zdGF0dXMu",
            "djEuU3RhdHVzIgAoAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NvidiaAce.Controller.V1.NvidiaAceControllerV1Reflection.Descriptor, global::NvidiaAce.Status.V1.NvidiaAceStatusV1Reflection.Descriptor, global::NvidiaAce.AnimationId.V1.NvidiaAceAnimationIdV1Reflection.Descriptor, global::NvidiaAce.AnimationData.V1.NvidiaAceAnimationDataV1Reflection.Descriptor, global::NvidiaAce.A2F.V1.NvidiaAceA2FV1Reflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest), global::NvidiaAce.Services.AnimationController.V1.AnimationGraphRequest.Parser, new[]{ "AnimationIds", "AnimationGraphVariableName", "AnimationGraphVariableValue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus), global::NvidiaAce.Services.AnimationController.V1.AnimationIdsOrStatus.Parser, new[]{ "AnimationIds", "Status" }, new[]{ "Response" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AnimationGraphRequest : pb::IMessage<AnimationGraphRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnimationGraphRequest> _parser = new pb::MessageParser<AnimationGraphRequest>(() => new AnimationGraphRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnimationGraphRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.Services.AnimationController.V1.NvidiaAceServicesAnimationControllerV1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationGraphRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationGraphRequest(AnimationGraphRequest other) : this() {
      animationIds_ = other.animationIds_ != null ? other.animationIds_.Clone() : null;
      animationGraphVariableName_ = other.animationGraphVariableName_;
      animationGraphVariableValue_ = other.animationGraphVariableValue_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationGraphRequest Clone() {
      return new AnimationGraphRequest(this);
    }

    /// <summary>Field number for the "animation_ids" field.</summary>
    public const int AnimationIdsFieldNumber = 1;
    private global::NvidiaAce.AnimationId.V1.AnimationIds animationIds_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.AnimationId.V1.AnimationIds AnimationIds {
      get { return animationIds_; }
      set {
        animationIds_ = value;
      }
    }

    /// <summary>Field number for the "animation_graph_variable_name" field.</summary>
    public const int AnimationGraphVariableNameFieldNumber = 2;
    private string animationGraphVariableName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AnimationGraphVariableName {
      get { return animationGraphVariableName_; }
      set {
        animationGraphVariableName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "animation_graph_variable_value" field.</summary>
    public const int AnimationGraphVariableValueFieldNumber = 3;
    private string animationGraphVariableValue_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AnimationGraphVariableValue {
      get { return animationGraphVariableValue_; }
      set {
        animationGraphVariableValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnimationGraphRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnimationGraphRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AnimationIds, other.AnimationIds)) return false;
      if (AnimationGraphVariableName != other.AnimationGraphVariableName) return false;
      if (AnimationGraphVariableValue != other.AnimationGraphVariableValue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (animationIds_ != null) hash ^= AnimationIds.GetHashCode();
      if (AnimationGraphVariableName.Length != 0) hash ^= AnimationGraphVariableName.GetHashCode();
      if (AnimationGraphVariableValue.Length != 0) hash ^= AnimationGraphVariableValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (animationIds_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AnimationIds);
      }
      if (AnimationGraphVariableName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AnimationGraphVariableName);
      }
      if (AnimationGraphVariableValue.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AnimationGraphVariableValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (animationIds_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AnimationIds);
      }
      if (AnimationGraphVariableName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AnimationGraphVariableName);
      }
      if (AnimationGraphVariableValue.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AnimationGraphVariableValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (animationIds_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnimationIds);
      }
      if (AnimationGraphVariableName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnimationGraphVariableName);
      }
      if (AnimationGraphVariableValue.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AnimationGraphVariableValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnimationGraphRequest other) {
      if (other == null) {
        return;
      }
      if (other.animationIds_ != null) {
        if (animationIds_ == null) {
          AnimationIds = new global::NvidiaAce.AnimationId.V1.AnimationIds();
        }
        AnimationIds.MergeFrom(other.AnimationIds);
      }
      if (other.AnimationGraphVariableName.Length != 0) {
        AnimationGraphVariableName = other.AnimationGraphVariableName;
      }
      if (other.AnimationGraphVariableValue.Length != 0) {
        AnimationGraphVariableValue = other.AnimationGraphVariableValue;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (animationIds_ == null) {
              AnimationIds = new global::NvidiaAce.AnimationId.V1.AnimationIds();
            }
            input.ReadMessage(AnimationIds);
            break;
          }
          case 18: {
            AnimationGraphVariableName = input.ReadString();
            break;
          }
          case 26: {
            AnimationGraphVariableValue = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (animationIds_ == null) {
              AnimationIds = new global::NvidiaAce.AnimationId.V1.AnimationIds();
            }
            input.ReadMessage(AnimationIds);
            break;
          }
          case 18: {
            AnimationGraphVariableName = input.ReadString();
            break;
          }
          case 26: {
            AnimationGraphVariableValue = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AnimationIdsOrStatus : pb::IMessage<AnimationIdsOrStatus>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnimationIdsOrStatus> _parser = new pb::MessageParser<AnimationIdsOrStatus>(() => new AnimationIdsOrStatus());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnimationIdsOrStatus> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.Services.AnimationController.V1.NvidiaAceServicesAnimationControllerV1Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationIdsOrStatus() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationIdsOrStatus(AnimationIdsOrStatus other) : this() {
      switch (other.ResponseCase) {
        case ResponseOneofCase.AnimationIds:
          AnimationIds = other.AnimationIds.Clone();
          break;
        case ResponseOneofCase.Status:
          Status = other.Status.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationIdsOrStatus Clone() {
      return new AnimationIdsOrStatus(this);
    }

    /// <summary>Field number for the "animation_ids" field.</summary>
    public const int AnimationIdsFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.AnimationId.V1.AnimationIds AnimationIds {
      get { return responseCase_ == ResponseOneofCase.AnimationIds ? (global::NvidiaAce.AnimationId.V1.AnimationIds) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.AnimationIds;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Status.V1.Status Status {
      get { return responseCase_ == ResponseOneofCase.Status ? (global::NvidiaAce.Status.V1.Status) response_ : null; }
      set {
        response_ = value;
        responseCase_ = value == null ? ResponseOneofCase.None : ResponseOneofCase.Status;
      }
    }

    private object response_;
    /// <summary>Enum of possible cases for the "response" oneof.</summary>
    public enum ResponseOneofCase {
      None = 0,
      AnimationIds = 1,
      Status = 2,
    }
    private ResponseOneofCase responseCase_ = ResponseOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseOneofCase ResponseCase {
      get { return responseCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResponse() {
      responseCase_ = ResponseOneofCase.None;
      response_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnimationIdsOrStatus);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnimationIdsOrStatus other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AnimationIds, other.AnimationIds)) return false;
      if (!object.Equals(Status, other.Status)) return false;
      if (ResponseCase != other.ResponseCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (responseCase_ == ResponseOneofCase.AnimationIds) hash ^= AnimationIds.GetHashCode();
      if (responseCase_ == ResponseOneofCase.Status) hash ^= Status.GetHashCode();
      hash ^= (int) responseCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (responseCase_ == ResponseOneofCase.AnimationIds) {
        output.WriteRawTag(10);
        output.WriteMessage(AnimationIds);
      }
      if (responseCase_ == ResponseOneofCase.Status) {
        output.WriteRawTag(18);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (responseCase_ == ResponseOneofCase.AnimationIds) {
        output.WriteRawTag(10);
        output.WriteMessage(AnimationIds);
      }
      if (responseCase_ == ResponseOneofCase.Status) {
        output.WriteRawTag(18);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (responseCase_ == ResponseOneofCase.AnimationIds) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnimationIds);
      }
      if (responseCase_ == ResponseOneofCase.Status) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnimationIdsOrStatus other) {
      if (other == null) {
        return;
      }
      switch (other.ResponseCase) {
        case ResponseOneofCase.AnimationIds:
          if (AnimationIds == null) {
            AnimationIds = new global::NvidiaAce.AnimationId.V1.AnimationIds();
          }
          AnimationIds.MergeFrom(other.AnimationIds);
          break;
        case ResponseOneofCase.Status:
          if (Status == null) {
            Status = new global::NvidiaAce.Status.V1.Status();
          }
          Status.MergeFrom(other.Status);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::NvidiaAce.AnimationId.V1.AnimationIds subBuilder = new global::NvidiaAce.AnimationId.V1.AnimationIds();
            if (responseCase_ == ResponseOneofCase.AnimationIds) {
              subBuilder.MergeFrom(AnimationIds);
            }
            input.ReadMessage(subBuilder);
            AnimationIds = subBuilder;
            break;
          }
          case 18: {
            global::NvidiaAce.Status.V1.Status subBuilder = new global::NvidiaAce.Status.V1.Status();
            if (responseCase_ == ResponseOneofCase.Status) {
              subBuilder.MergeFrom(Status);
            }
            input.ReadMessage(subBuilder);
            Status = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::NvidiaAce.AnimationId.V1.AnimationIds subBuilder = new global::NvidiaAce.AnimationId.V1.AnimationIds();
            if (responseCase_ == ResponseOneofCase.AnimationIds) {
              subBuilder.MergeFrom(AnimationIds);
            }
            input.ReadMessage(subBuilder);
            AnimationIds = subBuilder;
            break;
          }
          case 18: {
            global::NvidiaAce.Status.V1.Status subBuilder = new global::NvidiaAce.Status.V1.Status();
            if (responseCase_ == ResponseOneofCase.Status) {
              subBuilder.MergeFrom(Status);
            }
            input.ReadMessage(subBuilder);
            Status = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
