// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.a2f_authoring.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.A2FAuthoring.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.a2f_authoring.v1.proto</summary>
  public static partial class NvidiaAceA2FAuthoringV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.a2f_authoring.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceA2FAuthoringV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFudmlkaWFfYWNlLmEyZl9hdXRob3JpbmcudjEucHJvdG8SG252aWRpYV9h",
            "Y2UuYTJmX2F1dGhvcmluZy52MRoZbnZpZGlhX2FjZS5hdWRpby52MS5wcm90",
            "bxoXbnZpZGlhX2FjZS5hMmYudjEucHJvdG8iVAoJQXVkaW9DbGlwEjYKDGF1",
            "ZGlvX2hlYWRlchgBIAEoCzIgLm52aWRpYV9hY2UuYXVkaW8udjEuQXVkaW9I",
            "ZWFkZXISDwoHY29udGVudBgCIAEoDCJCCg9BdWRpb0NsaXBIYW5kbGUSFQoN",
            "YXVkaW9fY2xpcF9pZBgBIAEoCRIYChBibGVuZHNoYXBlX25hbWVzGAIgAygJ",
            "Ip8DCg9GYWNlUG9zZVJlcXVlc3QSEgoKYXVkaW9faGFzaBgBIAEoCRJfChJw",
            "cmVmZXJyZWRfZW1vdGlvbnMYAiADKAsyQy5udmlkaWFfYWNlLmEyZl9hdXRo",
            "b3JpbmcudjEuRmFjZVBvc2VSZXF1ZXN0LlByZWZlcnJlZEVtb3Rpb25zRW50",
            "cnkSEgoKdGltZV9zdGFtcBgDIAEoAhI2CgtmYWNlX3BhcmFtcxgEIAEoCzIh",
            "Lm52aWRpYV9hY2UuYTJmLnYxLkZhY2VQYXJhbWV0ZXJzEk0KEWVtb3Rpb25f",
            "cHBfcGFyYW1zGAUgASgLMjIubnZpZGlhX2FjZS5hMmYudjEuRW1vdGlvblBv",
            "c3RQcm9jZXNzaW5nUGFyYW1ldGVycxJCChFibGVuZHNoYXBlX3BhcmFtcxgG",
            "IAEoCzInLm52aWRpYV9hY2UuYTJmLnYxLkJsZW5kU2hhcGVQYXJhbWV0ZXJz",
            "GjgKFlByZWZlcnJlZEVtb3Rpb25zRW50cnkSCwoDa2V5GAEgASgJEg0KBXZh",
            "bHVlGAIgASgCOgI4ASK2AQoOQmxlbmRTaGFwZURhdGESEwoLYmxlbmRzaGFw",
            "ZXMYASADKAISEQoJdGltZV9jb2RlGAIgASgCEksKCGVtb3Rpb25zGAMgAygL",
            "MjkubnZpZGlhX2FjZS5hMmZfYXV0aG9yaW5nLnYxLkJsZW5kU2hhcGVEYXRh",
            "LkVtb3Rpb25zRW50cnkaLwoNRW1vdGlvbnNFbnRyeRILCgNrZXkYASABKAkS",
            "DQoFdmFsdWUYAiABKAI6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NvidiaAce.Audio.V1.NvidiaAceAudioV1Reflection.Descriptor, global::NvidiaAce.A2F.V1.NvidiaAceA2FV1Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.A2FAuthoring.V1.AudioClip), global::NvidiaAce.A2FAuthoring.V1.AudioClip.Parser, new[]{ "AudioHeader", "Content" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle), global::NvidiaAce.A2FAuthoring.V1.AudioClipHandle.Parser, new[]{ "AudioClipId", "BlendshapeNames" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest), global::NvidiaAce.A2FAuthoring.V1.FacePoseRequest.Parser, new[]{ "AudioHash", "PreferredEmotions", "TimeStamp", "FaceParams", "EmotionPpParams", "BlendshapeParams" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.A2FAuthoring.V1.BlendShapeData), global::NvidiaAce.A2FAuthoring.V1.BlendShapeData.Parser, new[]{ "Blendshapes", "TimeCode", "Emotions" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AudioClip : pb::IMessage<AudioClip>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioClip> _parser = new pb::MessageParser<AudioClip>(() => new AudioClip());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioClip> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.A2FAuthoring.V1.NvidiaAceA2FAuthoringV1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClip() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClip(AudioClip other) : this() {
      audioHeader_ = other.audioHeader_ != null ? other.audioHeader_.Clone() : null;
      content_ = other.content_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClip Clone() {
      return new AudioClip(this);
    }

    /// <summary>Field number for the "audio_header" field.</summary>
    public const int AudioHeaderFieldNumber = 1;
    private global::NvidiaAce.Audio.V1.AudioHeader audioHeader_;
    /// <summary>
    /// Audio header the appropriate metadata such as sample rate, etc
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Audio.V1.AudioHeader AudioHeader {
      get { return audioHeader_; }
      set {
        audioHeader_ = value;
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 2;
    private pb::ByteString content_ = pb::ByteString.Empty;
    /// <summary>
    /// Content of the audio file
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioClip);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioClip other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AudioHeader, other.AudioHeader)) return false;
      if (Content != other.Content) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (audioHeader_ != null) hash ^= AudioHeader.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (audioHeader_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AudioHeader);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (audioHeader_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AudioHeader);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Content);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (audioHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AudioHeader);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Content);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioClip other) {
      if (other == null) {
        return;
      }
      if (other.audioHeader_ != null) {
        if (audioHeader_ == null) {
          AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
        }
        AudioHeader.MergeFrom(other.AudioHeader);
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (audioHeader_ == null) {
              AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
            }
            input.ReadMessage(AudioHeader);
            break;
          }
          case 18: {
            Content = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (audioHeader_ == null) {
              AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
            }
            input.ReadMessage(AudioHeader);
            break;
          }
          case 18: {
            Content = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AudioClipHandle : pb::IMessage<AudioClipHandle>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioClipHandle> _parser = new pb::MessageParser<AudioClipHandle>(() => new AudioClipHandle());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioClipHandle> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.A2FAuthoring.V1.NvidiaAceA2FAuthoringV1Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClipHandle() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClipHandle(AudioClipHandle other) : this() {
      audioClipId_ = other.audioClipId_;
      blendshapeNames_ = other.blendshapeNames_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioClipHandle Clone() {
      return new AudioClipHandle(this);
    }

    /// <summary>Field number for the "audio_clip_id" field.</summary>
    public const int AudioClipIdFieldNumber = 1;
    private string audioClipId_ = "";
    /// <summary>
    /// SHA-256 hash of the audio clip.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AudioClipId {
      get { return audioClipId_; }
      set {
        audioClipId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "blendshape_names" field.</summary>
    public const int BlendshapeNamesFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_blendshapeNames_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> blendshapeNames_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Names of the blendshapes that will be sent back to the client.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> BlendshapeNames {
      get { return blendshapeNames_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioClipHandle);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioClipHandle other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AudioClipId != other.AudioClipId) return false;
      if(!blendshapeNames_.Equals(other.blendshapeNames_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AudioClipId.Length != 0) hash ^= AudioClipId.GetHashCode();
      hash ^= blendshapeNames_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AudioClipId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AudioClipId);
      }
      blendshapeNames_.WriteTo(output, _repeated_blendshapeNames_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AudioClipId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AudioClipId);
      }
      blendshapeNames_.WriteTo(ref output, _repeated_blendshapeNames_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AudioClipId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AudioClipId);
      }
      size += blendshapeNames_.CalculateSize(_repeated_blendshapeNames_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioClipHandle other) {
      if (other == null) {
        return;
      }
      if (other.AudioClipId.Length != 0) {
        AudioClipId = other.AudioClipId;
      }
      blendshapeNames_.Add(other.blendshapeNames_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AudioClipId = input.ReadString();
            break;
          }
          case 18: {
            blendshapeNames_.AddEntriesFrom(input, _repeated_blendshapeNames_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AudioClipId = input.ReadString();
            break;
          }
          case 18: {
            blendshapeNames_.AddEntriesFrom(ref input, _repeated_blendshapeNames_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FacePoseRequest : pb::IMessage<FacePoseRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FacePoseRequest> _parser = new pb::MessageParser<FacePoseRequest>(() => new FacePoseRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FacePoseRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.A2FAuthoring.V1.NvidiaAceA2FAuthoringV1Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FacePoseRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FacePoseRequest(FacePoseRequest other) : this() {
      audioHash_ = other.audioHash_;
      preferredEmotions_ = other.preferredEmotions_.Clone();
      timeStamp_ = other.timeStamp_;
      faceParams_ = other.faceParams_ != null ? other.faceParams_.Clone() : null;
      emotionPpParams_ = other.emotionPpParams_ != null ? other.emotionPpParams_.Clone() : null;
      blendshapeParams_ = other.blendshapeParams_ != null ? other.blendshapeParams_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FacePoseRequest Clone() {
      return new FacePoseRequest(this);
    }

    /// <summary>Field number for the "audio_hash" field.</summary>
    public const int AudioHashFieldNumber = 1;
    private string audioHash_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AudioHash {
      get { return audioHash_; }
      set {
        audioHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "preferred_emotions" field.</summary>
    public const int PreferredEmotionsFieldNumber = 2;
    private static readonly pbc::MapField<string, float>.Codec _map_preferredEmotions_codec
        = new pbc::MapField<string, float>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForFloat(21, 0F), 18);
    private readonly pbc::MapField<string, float> preferredEmotions_ = new pbc::MapField<string, float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, float> PreferredEmotions {
      get { return preferredEmotions_; }
    }

    /// <summary>Field number for the "time_stamp" field.</summary>
    public const int TimeStampFieldNumber = 3;
    private float timeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = value;
      }
    }

    /// <summary>Field number for the "face_params" field.</summary>
    public const int FaceParamsFieldNumber = 4;
    private global::NvidiaAce.A2F.V1.FaceParameters faceParams_;
    /// <summary>
    /// Parameters for updating the facial characteristics of an avatar
    /// See the documentation for more information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.A2F.V1.FaceParameters FaceParams {
      get { return faceParams_; }
      set {
        faceParams_ = value;
      }
    }

    /// <summary>Field number for the "emotion_pp_params" field.</summary>
    public const int EmotionPpParamsFieldNumber = 5;
    private global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters emotionPpParams_;
    /// <summary>
    /// Parameters relative to the emotion blending and processing
    /// before using it to generate blendshapes
    /// See the documentation for more information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters EmotionPpParams {
      get { return emotionPpParams_; }
      set {
        emotionPpParams_ = value;
      }
    }

    /// <summary>Field number for the "blendshape_params" field.</summary>
    public const int BlendshapeParamsFieldNumber = 6;
    private global::NvidiaAce.A2F.V1.BlendShapeParameters blendshapeParams_;
    /// <summary>
    /// Multipliers and offsets to apply to the generated blendshapes values
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.A2F.V1.BlendShapeParameters BlendshapeParams {
      get { return blendshapeParams_; }
      set {
        blendshapeParams_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FacePoseRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FacePoseRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AudioHash != other.AudioHash) return false;
      if (!PreferredEmotions.Equals(other.PreferredEmotions)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TimeStamp, other.TimeStamp)) return false;
      if (!object.Equals(FaceParams, other.FaceParams)) return false;
      if (!object.Equals(EmotionPpParams, other.EmotionPpParams)) return false;
      if (!object.Equals(BlendshapeParams, other.BlendshapeParams)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AudioHash.Length != 0) hash ^= AudioHash.GetHashCode();
      hash ^= PreferredEmotions.GetHashCode();
      if (TimeStamp != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TimeStamp);
      if (faceParams_ != null) hash ^= FaceParams.GetHashCode();
      if (emotionPpParams_ != null) hash ^= EmotionPpParams.GetHashCode();
      if (blendshapeParams_ != null) hash ^= BlendshapeParams.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AudioHash.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AudioHash);
      }
      preferredEmotions_.WriteTo(output, _map_preferredEmotions_codec);
      if (TimeStamp != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(TimeStamp);
      }
      if (faceParams_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceParams);
      }
      if (emotionPpParams_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(EmotionPpParams);
      }
      if (blendshapeParams_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(BlendshapeParams);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AudioHash.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AudioHash);
      }
      preferredEmotions_.WriteTo(ref output, _map_preferredEmotions_codec);
      if (TimeStamp != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(TimeStamp);
      }
      if (faceParams_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(FaceParams);
      }
      if (emotionPpParams_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(EmotionPpParams);
      }
      if (blendshapeParams_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(BlendshapeParams);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AudioHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AudioHash);
      }
      size += preferredEmotions_.CalculateSize(_map_preferredEmotions_codec);
      if (TimeStamp != 0F) {
        size += 1 + 4;
      }
      if (faceParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceParams);
      }
      if (emotionPpParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EmotionPpParams);
      }
      if (blendshapeParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BlendshapeParams);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FacePoseRequest other) {
      if (other == null) {
        return;
      }
      if (other.AudioHash.Length != 0) {
        AudioHash = other.AudioHash;
      }
      preferredEmotions_.MergeFrom(other.preferredEmotions_);
      if (other.TimeStamp != 0F) {
        TimeStamp = other.TimeStamp;
      }
      if (other.faceParams_ != null) {
        if (faceParams_ == null) {
          FaceParams = new global::NvidiaAce.A2F.V1.FaceParameters();
        }
        FaceParams.MergeFrom(other.FaceParams);
      }
      if (other.emotionPpParams_ != null) {
        if (emotionPpParams_ == null) {
          EmotionPpParams = new global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters();
        }
        EmotionPpParams.MergeFrom(other.EmotionPpParams);
      }
      if (other.blendshapeParams_ != null) {
        if (blendshapeParams_ == null) {
          BlendshapeParams = new global::NvidiaAce.A2F.V1.BlendShapeParameters();
        }
        BlendshapeParams.MergeFrom(other.BlendshapeParams);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AudioHash = input.ReadString();
            break;
          }
          case 18: {
            preferredEmotions_.AddEntriesFrom(input, _map_preferredEmotions_codec);
            break;
          }
          case 29: {
            TimeStamp = input.ReadFloat();
            break;
          }
          case 34: {
            if (faceParams_ == null) {
              FaceParams = new global::NvidiaAce.A2F.V1.FaceParameters();
            }
            input.ReadMessage(FaceParams);
            break;
          }
          case 42: {
            if (emotionPpParams_ == null) {
              EmotionPpParams = new global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters();
            }
            input.ReadMessage(EmotionPpParams);
            break;
          }
          case 50: {
            if (blendshapeParams_ == null) {
              BlendshapeParams = new global::NvidiaAce.A2F.V1.BlendShapeParameters();
            }
            input.ReadMessage(BlendshapeParams);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AudioHash = input.ReadString();
            break;
          }
          case 18: {
            preferredEmotions_.AddEntriesFrom(ref input, _map_preferredEmotions_codec);
            break;
          }
          case 29: {
            TimeStamp = input.ReadFloat();
            break;
          }
          case 34: {
            if (faceParams_ == null) {
              FaceParams = new global::NvidiaAce.A2F.V1.FaceParameters();
            }
            input.ReadMessage(FaceParams);
            break;
          }
          case 42: {
            if (emotionPpParams_ == null) {
              EmotionPpParams = new global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters();
            }
            input.ReadMessage(EmotionPpParams);
            break;
          }
          case 50: {
            if (blendshapeParams_ == null) {
              BlendshapeParams = new global::NvidiaAce.A2F.V1.BlendShapeParameters();
            }
            input.ReadMessage(BlendshapeParams);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BlendShapeData : pb::IMessage<BlendShapeData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BlendShapeData> _parser = new pb::MessageParser<BlendShapeData>(() => new BlendShapeData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BlendShapeData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.A2FAuthoring.V1.NvidiaAceA2FAuthoringV1Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlendShapeData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlendShapeData(BlendShapeData other) : this() {
      blendshapes_ = other.blendshapes_.Clone();
      timeCode_ = other.timeCode_;
      emotions_ = other.emotions_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BlendShapeData Clone() {
      return new BlendShapeData(this);
    }

    /// <summary>Field number for the "blendshapes" field.</summary>
    public const int BlendshapesFieldNumber = 1;
    private static readonly pb::FieldCodec<float> _repeated_blendshapes_codec
        = pb::FieldCodec.ForFloat(10);
    private readonly pbc::RepeatedField<float> blendshapes_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// Blendshapes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Blendshapes {
      get { return blendshapes_; }
    }

    /// <summary>Field number for the "time_code" field.</summary>
    public const int TimeCodeFieldNumber = 2;
    private float timeCode_;
    /// <summary>
    /// Echo the time_code for the frame.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TimeCode {
      get { return timeCode_; }
      set {
        timeCode_ = value;
      }
    }

    /// <summary>Field number for the "emotions" field.</summary>
    public const int EmotionsFieldNumber = 3;
    private static readonly pbc::MapField<string, float>.Codec _map_emotions_codec
        = new pbc::MapField<string, float>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForFloat(21, 0F), 26);
    private readonly pbc::MapField<string, float> emotions_ = new pbc::MapField<string, float>();
    /// <summary>
    /// Emotion output from A2E after post-processing (Applied emotions).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, float> Emotions {
      get { return emotions_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BlendShapeData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BlendShapeData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!blendshapes_.Equals(other.blendshapes_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TimeCode, other.TimeCode)) return false;
      if (!Emotions.Equals(other.Emotions)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= blendshapes_.GetHashCode();
      if (TimeCode != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TimeCode);
      hash ^= Emotions.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      blendshapes_.WriteTo(output, _repeated_blendshapes_codec);
      if (TimeCode != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(TimeCode);
      }
      emotions_.WriteTo(output, _map_emotions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      blendshapes_.WriteTo(ref output, _repeated_blendshapes_codec);
      if (TimeCode != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(TimeCode);
      }
      emotions_.WriteTo(ref output, _map_emotions_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += blendshapes_.CalculateSize(_repeated_blendshapes_codec);
      if (TimeCode != 0F) {
        size += 1 + 4;
      }
      size += emotions_.CalculateSize(_map_emotions_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BlendShapeData other) {
      if (other == null) {
        return;
      }
      blendshapes_.Add(other.blendshapes_);
      if (other.TimeCode != 0F) {
        TimeCode = other.TimeCode;
      }
      emotions_.MergeFrom(other.emotions_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 13: {
            blendshapes_.AddEntriesFrom(input, _repeated_blendshapes_codec);
            break;
          }
          case 21: {
            TimeCode = input.ReadFloat();
            break;
          }
          case 26: {
            emotions_.AddEntriesFrom(input, _map_emotions_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 13: {
            blendshapes_.AddEntriesFrom(ref input, _repeated_blendshapes_codec);
            break;
          }
          case 21: {
            TimeCode = input.ReadFloat();
            break;
          }
          case 26: {
            emotions_.AddEntriesFrom(ref input, _map_emotions_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
