// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: nvidia_ace.controller.v1.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NvidiaAce.Controller.V1 {

  /// <summary>Holder for reflection information generated from nvidia_ace.controller.v1.proto</summary>
  public static partial class NvidiaAceControllerV1Reflection {

    #region Descriptor
    /// <summary>File descriptor for nvidia_ace.controller.v1.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NvidiaAceControllerV1Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5udmlkaWFfYWNlLmNvbnRyb2xsZXIudjEucHJvdG8SGG52aWRpYV9hY2Uu",
            "Y29udHJvbGxlci52MRoXbnZpZGlhX2FjZS5hMmYudjEucHJvdG8aIm52aWRp",
            "YV9hY2UuYW5pbWF0aW9uX2RhdGEudjEucHJvdG8aGW52aWRpYV9hY2UuYXVk",
            "aW8udjEucHJvdG8aGm52aWRpYV9hY2Uuc3RhdHVzLnYxLnByb3RvGhlnb29n",
            "bGUvcHJvdG9idWYvYW55LnByb3RvIoMCCgtBdWRpb1N0cmVhbRJKChNhdWRp",
            "b19zdHJlYW1faGVhZGVyGAEgASgLMisubnZpZGlhX2FjZS5jb250cm9sbGVy",
            "LnYxLkF1ZGlvU3RyZWFtSGVhZGVySAASQQoSYXVkaW9fd2l0aF9lbW90aW9u",
            "GAIgASgLMiMubnZpZGlhX2FjZS5hMmYudjEuQXVkaW9XaXRoRW1vdGlvbkgA",
            "EkgKDGVuZF9vZl9hdWRpbxgDIAEoCzIwLm52aWRpYV9hY2UuY29udHJvbGxl",
            "ci52MS5BdWRpb1N0cmVhbS5FbmRPZkF1ZGlvSAAaDAoKRW5kT2ZBdWRpb0IN",
            "CgtzdHJlYW1fcGFydCLhAgoRQXVkaW9TdHJlYW1IZWFkZXISNgoMYXVkaW9f",
            "aGVhZGVyGAEgASgLMiAubnZpZGlhX2FjZS5hdWRpby52MS5BdWRpb0hlYWRl",
            "chI2CgtmYWNlX3BhcmFtcxgCIAEoCzIhLm52aWRpYV9hY2UuYTJmLnYxLkZh",
            "Y2VQYXJhbWV0ZXJzEloKHmVtb3Rpb25fcG9zdF9wcm9jZXNzaW5nX3BhcmFt",
            "cxgDIAEoCzIyLm52aWRpYV9hY2UuYTJmLnYxLkVtb3Rpb25Qb3N0UHJvY2Vz",
            "c2luZ1BhcmFtZXRlcnMSQgoRYmxlbmRzaGFwZV9wYXJhbXMYBCABKAsyJy5u",
            "dmlkaWFfYWNlLmEyZi52MS5CbGVuZFNoYXBlUGFyYW1ldGVycxI8Cg5lbW90",
            "aW9uX3BhcmFtcxgFIAEoCzIkLm52aWRpYV9hY2UuYTJmLnYxLkVtb3Rpb25Q",
            "YXJhbWV0ZXJzInoKBUV2ZW50EjcKCmV2ZW50X3R5cGUYASABKA4yIy5udmlk",
            "aWFfYWNlLmNvbnRyb2xsZXIudjEuRXZlbnRUeXBlEisKCG1ldGFkYXRhGAIg",
            "ASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueUgAiAEBQgsKCV9tZXRhZGF0YSL/",
            "AQoZQW5pbWF0aW9uRGF0YVN0cmVhbUhlYWRlchI7CgxhdWRpb19oZWFkZXIY",
            "ASABKAsyIC5udmlkaWFfYWNlLmF1ZGlvLnYxLkF1ZGlvSGVhZGVySACIAQES",
            "VQoVc2tlbF9hbmltYXRpb25faGVhZGVyGAIgASgLMjEubnZpZGlhX2FjZS5h",
            "bmltYXRpb25fZGF0YS52MS5Ta2VsQW5pbWF0aW9uSGVhZGVySAGIAQESIwob",
            "c3RhcnRfdGltZV9jb2RlX3NpbmNlX2Vwb2NoGAMgASgBQg8KDV9hdWRpb19o",
            "ZWFkZXJCGAoWX3NrZWxfYW5pbWF0aW9uX2hlYWRlciKqAgoTQW5pbWF0aW9u",
            "RGF0YVN0cmVhbRJbChxhbmltYXRpb25fZGF0YV9zdHJlYW1faGVhZGVyGAEg",
            "ASgLMjMubnZpZGlhX2FjZS5jb250cm9sbGVyLnYxLkFuaW1hdGlvbkRhdGFT",
            "dHJlYW1IZWFkZXJIABJFCg5hbmltYXRpb25fZGF0YRgCIAEoCzIrLm52aWRp",
            "YV9hY2UuYW5pbWF0aW9uX2RhdGEudjEuQW5pbWF0aW9uRGF0YUgAEjAKBWV2",
            "ZW50GAMgASgLMh8ubnZpZGlhX2FjZS5jb250cm9sbGVyLnYxLkV2ZW50SAAS",
            "LgoGc3RhdHVzGAQgASgLMhwubnZpZGlhX2FjZS5zdGF0dXMudjEuU3RhdHVz",
            "SABCDQoLc3RyZWFtX3BhcnQqLAoJRXZlbnRUeXBlEh8KG0VORF9PRl9BMkZf",
            "QVVESU9fUFJPQ0VTU0lORxAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NvidiaAce.A2F.V1.NvidiaAceA2FV1Reflection.Descriptor, global::NvidiaAce.AnimationData.V1.NvidiaAceAnimationDataV1Reflection.Descriptor, global::NvidiaAce.Audio.V1.NvidiaAceAudioV1Reflection.Descriptor, global::NvidiaAce.Status.V1.NvidiaAceStatusV1Reflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NvidiaAce.Controller.V1.EventType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Controller.V1.AudioStream), global::NvidiaAce.Controller.V1.AudioStream.Parser, new[]{ "AudioStreamHeader", "AudioWithEmotion", "EndOfAudio" }, new[]{ "StreamPart" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio), global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio.Parser, null, null, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Controller.V1.AudioStreamHeader), global::NvidiaAce.Controller.V1.AudioStreamHeader.Parser, new[]{ "AudioHeader", "FaceParams", "EmotionPostProcessingParams", "BlendshapeParams", "EmotionParams" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Controller.V1.Event), global::NvidiaAce.Controller.V1.Event.Parser, new[]{ "EventType", "Metadata" }, new[]{ "Metadata" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Controller.V1.AnimationDataStreamHeader), global::NvidiaAce.Controller.V1.AnimationDataStreamHeader.Parser, new[]{ "AudioHeader", "SkelAnimationHeader", "StartTimeCodeSinceEpoch" }, new[]{ "AudioHeader", "SkelAnimationHeader" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NvidiaAce.Controller.V1.AnimationDataStream), global::NvidiaAce.Controller.V1.AnimationDataStream.Parser, new[]{ "AnimationDataStreamHeader", "AnimationData", "Event", "Status" }, new[]{ "StreamPart" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EventType {
    /// <summary>
    /// This event type means that the A2F Microservice is done processing audio,
    /// However it doesn't mean that you finished receiving all the audio data,
    /// You will receive a Status message once you are done receiving all the audio
    /// data. Events are independent of that.
    /// </summary>
    [pbr::OriginalName("END_OF_A2F_AUDIO_PROCESSING")] EndOfA2FAudioProcessing = 0,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AudioStream : pb::IMessage<AudioStream>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioStream> _parser = new pb::MessageParser<AudioStream>(() => new AudioStream());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioStream> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.Controller.V1.NvidiaAceControllerV1Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioStream() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioStream(AudioStream other) : this() {
      switch (other.StreamPartCase) {
        case StreamPartOneofCase.AudioStreamHeader:
          AudioStreamHeader = other.AudioStreamHeader.Clone();
          break;
        case StreamPartOneofCase.AudioWithEmotion:
          AudioWithEmotion = other.AudioWithEmotion.Clone();
          break;
        case StreamPartOneofCase.EndOfAudio:
          EndOfAudio = other.EndOfAudio.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioStream Clone() {
      return new AudioStream(this);
    }

    /// <summary>Field number for the "audio_stream_header" field.</summary>
    public const int AudioStreamHeaderFieldNumber = 1;
    /// <summary>
    /// The header must be sent as the first message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Controller.V1.AudioStreamHeader AudioStreamHeader {
      get { return streamPartCase_ == StreamPartOneofCase.AudioStreamHeader ? (global::NvidiaAce.Controller.V1.AudioStreamHeader) streamPart_ : null; }
      set {
        streamPart_ = value;
        streamPartCase_ = value == null ? StreamPartOneofCase.None : StreamPartOneofCase.AudioStreamHeader;
      }
    }

    /// <summary>Field number for the "audio_with_emotion" field.</summary>
    public const int AudioWithEmotionFieldNumber = 2;
    /// <summary>
    /// At least one AudioWithEmotion messages must be sent thereafter.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.A2F.V1.AudioWithEmotion AudioWithEmotion {
      get { return streamPartCase_ == StreamPartOneofCase.AudioWithEmotion ? (global::NvidiaAce.A2F.V1.AudioWithEmotion) streamPart_ : null; }
      set {
        streamPart_ = value;
        streamPartCase_ = value == null ? StreamPartOneofCase.None : StreamPartOneofCase.AudioWithEmotion;
      }
    }

    /// <summary>Field number for the "end_of_audio" field.</summary>
    public const int EndOfAudioFieldNumber = 3;
    /// <summary>
    /// The EndOfAudio must be sent last.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio EndOfAudio {
      get { return streamPartCase_ == StreamPartOneofCase.EndOfAudio ? (global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio) streamPart_ : null; }
      set {
        streamPart_ = value;
        streamPartCase_ = value == null ? StreamPartOneofCase.None : StreamPartOneofCase.EndOfAudio;
      }
    }

    private object streamPart_;
    /// <summary>Enum of possible cases for the "stream_part" oneof.</summary>
    public enum StreamPartOneofCase {
      None = 0,
      AudioStreamHeader = 1,
      AudioWithEmotion = 2,
      EndOfAudio = 3,
    }
    private StreamPartOneofCase streamPartCase_ = StreamPartOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StreamPartOneofCase StreamPartCase {
      get { return streamPartCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStreamPart() {
      streamPartCase_ = StreamPartOneofCase.None;
      streamPart_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioStream);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioStream other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AudioStreamHeader, other.AudioStreamHeader)) return false;
      if (!object.Equals(AudioWithEmotion, other.AudioWithEmotion)) return false;
      if (!object.Equals(EndOfAudio, other.EndOfAudio)) return false;
      if (StreamPartCase != other.StreamPartCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (streamPartCase_ == StreamPartOneofCase.AudioStreamHeader) hash ^= AudioStreamHeader.GetHashCode();
      if (streamPartCase_ == StreamPartOneofCase.AudioWithEmotion) hash ^= AudioWithEmotion.GetHashCode();
      if (streamPartCase_ == StreamPartOneofCase.EndOfAudio) hash ^= EndOfAudio.GetHashCode();
      hash ^= (int) streamPartCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (streamPartCase_ == StreamPartOneofCase.AudioStreamHeader) {
        output.WriteRawTag(10);
        output.WriteMessage(AudioStreamHeader);
      }
      if (streamPartCase_ == StreamPartOneofCase.AudioWithEmotion) {
        output.WriteRawTag(18);
        output.WriteMessage(AudioWithEmotion);
      }
      if (streamPartCase_ == StreamPartOneofCase.EndOfAudio) {
        output.WriteRawTag(26);
        output.WriteMessage(EndOfAudio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (streamPartCase_ == StreamPartOneofCase.AudioStreamHeader) {
        output.WriteRawTag(10);
        output.WriteMessage(AudioStreamHeader);
      }
      if (streamPartCase_ == StreamPartOneofCase.AudioWithEmotion) {
        output.WriteRawTag(18);
        output.WriteMessage(AudioWithEmotion);
      }
      if (streamPartCase_ == StreamPartOneofCase.EndOfAudio) {
        output.WriteRawTag(26);
        output.WriteMessage(EndOfAudio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (streamPartCase_ == StreamPartOneofCase.AudioStreamHeader) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AudioStreamHeader);
      }
      if (streamPartCase_ == StreamPartOneofCase.AudioWithEmotion) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AudioWithEmotion);
      }
      if (streamPartCase_ == StreamPartOneofCase.EndOfAudio) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndOfAudio);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioStream other) {
      if (other == null) {
        return;
      }
      switch (other.StreamPartCase) {
        case StreamPartOneofCase.AudioStreamHeader:
          if (AudioStreamHeader == null) {
            AudioStreamHeader = new global::NvidiaAce.Controller.V1.AudioStreamHeader();
          }
          AudioStreamHeader.MergeFrom(other.AudioStreamHeader);
          break;
        case StreamPartOneofCase.AudioWithEmotion:
          if (AudioWithEmotion == null) {
            AudioWithEmotion = new global::NvidiaAce.A2F.V1.AudioWithEmotion();
          }
          AudioWithEmotion.MergeFrom(other.AudioWithEmotion);
          break;
        case StreamPartOneofCase.EndOfAudio:
          if (EndOfAudio == null) {
            EndOfAudio = new global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio();
          }
          EndOfAudio.MergeFrom(other.EndOfAudio);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::NvidiaAce.Controller.V1.AudioStreamHeader subBuilder = new global::NvidiaAce.Controller.V1.AudioStreamHeader();
            if (streamPartCase_ == StreamPartOneofCase.AudioStreamHeader) {
              subBuilder.MergeFrom(AudioStreamHeader);
            }
            input.ReadMessage(subBuilder);
            AudioStreamHeader = subBuilder;
            break;
          }
          case 18: {
            global::NvidiaAce.A2F.V1.AudioWithEmotion subBuilder = new global::NvidiaAce.A2F.V1.AudioWithEmotion();
            if (streamPartCase_ == StreamPartOneofCase.AudioWithEmotion) {
              subBuilder.MergeFrom(AudioWithEmotion);
            }
            input.ReadMessage(subBuilder);
            AudioWithEmotion = subBuilder;
            break;
          }
          case 26: {
            global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio subBuilder = new global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio();
            if (streamPartCase_ == StreamPartOneofCase.EndOfAudio) {
              subBuilder.MergeFrom(EndOfAudio);
            }
            input.ReadMessage(subBuilder);
            EndOfAudio = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::NvidiaAce.Controller.V1.AudioStreamHeader subBuilder = new global::NvidiaAce.Controller.V1.AudioStreamHeader();
            if (streamPartCase_ == StreamPartOneofCase.AudioStreamHeader) {
              subBuilder.MergeFrom(AudioStreamHeader);
            }
            input.ReadMessage(subBuilder);
            AudioStreamHeader = subBuilder;
            break;
          }
          case 18: {
            global::NvidiaAce.A2F.V1.AudioWithEmotion subBuilder = new global::NvidiaAce.A2F.V1.AudioWithEmotion();
            if (streamPartCase_ == StreamPartOneofCase.AudioWithEmotion) {
              subBuilder.MergeFrom(AudioWithEmotion);
            }
            input.ReadMessage(subBuilder);
            AudioWithEmotion = subBuilder;
            break;
          }
          case 26: {
            global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio subBuilder = new global::NvidiaAce.Controller.V1.AudioStream.Types.EndOfAudio();
            if (streamPartCase_ == StreamPartOneofCase.EndOfAudio) {
              subBuilder.MergeFrom(EndOfAudio);
            }
            input.ReadMessage(subBuilder);
            EndOfAudio = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the AudioStream message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// This is a marker for the end of an audio clip.
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class EndOfAudio : pb::IMessage<EndOfAudio>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<EndOfAudio> _parser = new pb::MessageParser<EndOfAudio>(() => new EndOfAudio());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<EndOfAudio> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::NvidiaAce.Controller.V1.AudioStream.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EndOfAudio() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EndOfAudio(EndOfAudio other) : this() {
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public EndOfAudio Clone() {
          return new EndOfAudio(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as EndOfAudio);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(EndOfAudio other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(EndOfAudio other) {
          if (other == null) {
            return;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  /// <summary>
  /// IMPORTANT NOTE: this is an AudioStreamHeader WITHOUT ID
  /// A similar AudioStreamHeader exist in nvidia_ace.a2f.v1.proto
  /// but that one does contain IDs.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AudioStreamHeader : pb::IMessage<AudioStreamHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AudioStreamHeader> _parser = new pb::MessageParser<AudioStreamHeader>(() => new AudioStreamHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AudioStreamHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.Controller.V1.NvidiaAceControllerV1Reflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioStreamHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioStreamHeader(AudioStreamHeader other) : this() {
      audioHeader_ = other.audioHeader_ != null ? other.audioHeader_.Clone() : null;
      faceParams_ = other.faceParams_ != null ? other.faceParams_.Clone() : null;
      emotionPostProcessingParams_ = other.emotionPostProcessingParams_ != null ? other.emotionPostProcessingParams_.Clone() : null;
      blendshapeParams_ = other.blendshapeParams_ != null ? other.blendshapeParams_.Clone() : null;
      emotionParams_ = other.emotionParams_ != null ? other.emotionParams_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AudioStreamHeader Clone() {
      return new AudioStreamHeader(this);
    }

    /// <summary>Field number for the "audio_header" field.</summary>
    public const int AudioHeaderFieldNumber = 1;
    private global::NvidiaAce.Audio.V1.AudioHeader audioHeader_;
    /// <summary>
    /// Metadata about the audio being sent to the service.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Audio.V1.AudioHeader AudioHeader {
      get { return audioHeader_; }
      set {
        audioHeader_ = value;
      }
    }

    /// <summary>Field number for the "face_params" field.</summary>
    public const int FaceParamsFieldNumber = 2;
    private global::NvidiaAce.A2F.V1.FaceParameters faceParams_;
    /// <summary>
    /// Parameters for updating the facial characteristics of an avatar.
    /// See the documentation for more information.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.A2F.V1.FaceParameters FaceParams {
      get { return faceParams_; }
      set {
        faceParams_ = value;
      }
    }

    /// <summary>Field number for the "emotion_post_processing_params" field.</summary>
    public const int EmotionPostProcessingParamsFieldNumber = 3;
    private global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters emotionPostProcessingParams_;
    /// <summary>
    /// Parameters relative to the emotion blending and processing
    /// before using it to generate blendshapes.
    /// See the documentation for more information.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters EmotionPostProcessingParams {
      get { return emotionPostProcessingParams_; }
      set {
        emotionPostProcessingParams_ = value;
      }
    }

    /// <summary>Field number for the "blendshape_params" field.</summary>
    public const int BlendshapeParamsFieldNumber = 4;
    private global::NvidiaAce.A2F.V1.BlendShapeParameters blendshapeParams_;
    /// <summary>
    /// Multipliers and offsets to apply to the generated blendshape values.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.A2F.V1.BlendShapeParameters BlendshapeParams {
      get { return blendshapeParams_; }
      set {
        blendshapeParams_ = value;
      }
    }

    /// <summary>Field number for the "emotion_params" field.</summary>
    public const int EmotionParamsFieldNumber = 5;
    private global::NvidiaAce.A2F.V1.EmotionParameters emotionParams_;
    /// <summary>
    /// Emotion parameters (live transition time, beginning emotion)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.A2F.V1.EmotionParameters EmotionParams {
      get { return emotionParams_; }
      set {
        emotionParams_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AudioStreamHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AudioStreamHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AudioHeader, other.AudioHeader)) return false;
      if (!object.Equals(FaceParams, other.FaceParams)) return false;
      if (!object.Equals(EmotionPostProcessingParams, other.EmotionPostProcessingParams)) return false;
      if (!object.Equals(BlendshapeParams, other.BlendshapeParams)) return false;
      if (!object.Equals(EmotionParams, other.EmotionParams)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (audioHeader_ != null) hash ^= AudioHeader.GetHashCode();
      if (faceParams_ != null) hash ^= FaceParams.GetHashCode();
      if (emotionPostProcessingParams_ != null) hash ^= EmotionPostProcessingParams.GetHashCode();
      if (blendshapeParams_ != null) hash ^= BlendshapeParams.GetHashCode();
      if (emotionParams_ != null) hash ^= EmotionParams.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (audioHeader_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AudioHeader);
      }
      if (faceParams_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FaceParams);
      }
      if (emotionPostProcessingParams_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(EmotionPostProcessingParams);
      }
      if (blendshapeParams_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BlendshapeParams);
      }
      if (emotionParams_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(EmotionParams);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (audioHeader_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AudioHeader);
      }
      if (faceParams_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FaceParams);
      }
      if (emotionPostProcessingParams_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(EmotionPostProcessingParams);
      }
      if (blendshapeParams_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BlendshapeParams);
      }
      if (emotionParams_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(EmotionParams);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (audioHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AudioHeader);
      }
      if (faceParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FaceParams);
      }
      if (emotionPostProcessingParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EmotionPostProcessingParams);
      }
      if (blendshapeParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BlendshapeParams);
      }
      if (emotionParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EmotionParams);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AudioStreamHeader other) {
      if (other == null) {
        return;
      }
      if (other.audioHeader_ != null) {
        if (audioHeader_ == null) {
          AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
        }
        AudioHeader.MergeFrom(other.AudioHeader);
      }
      if (other.faceParams_ != null) {
        if (faceParams_ == null) {
          FaceParams = new global::NvidiaAce.A2F.V1.FaceParameters();
        }
        FaceParams.MergeFrom(other.FaceParams);
      }
      if (other.emotionPostProcessingParams_ != null) {
        if (emotionPostProcessingParams_ == null) {
          EmotionPostProcessingParams = new global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters();
        }
        EmotionPostProcessingParams.MergeFrom(other.EmotionPostProcessingParams);
      }
      if (other.blendshapeParams_ != null) {
        if (blendshapeParams_ == null) {
          BlendshapeParams = new global::NvidiaAce.A2F.V1.BlendShapeParameters();
        }
        BlendshapeParams.MergeFrom(other.BlendshapeParams);
      }
      if (other.emotionParams_ != null) {
        if (emotionParams_ == null) {
          EmotionParams = new global::NvidiaAce.A2F.V1.EmotionParameters();
        }
        EmotionParams.MergeFrom(other.EmotionParams);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (audioHeader_ == null) {
              AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
            }
            input.ReadMessage(AudioHeader);
            break;
          }
          case 18: {
            if (faceParams_ == null) {
              FaceParams = new global::NvidiaAce.A2F.V1.FaceParameters();
            }
            input.ReadMessage(FaceParams);
            break;
          }
          case 26: {
            if (emotionPostProcessingParams_ == null) {
              EmotionPostProcessingParams = new global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters();
            }
            input.ReadMessage(EmotionPostProcessingParams);
            break;
          }
          case 34: {
            if (blendshapeParams_ == null) {
              BlendshapeParams = new global::NvidiaAce.A2F.V1.BlendShapeParameters();
            }
            input.ReadMessage(BlendshapeParams);
            break;
          }
          case 42: {
            if (emotionParams_ == null) {
              EmotionParams = new global::NvidiaAce.A2F.V1.EmotionParameters();
            }
            input.ReadMessage(EmotionParams);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (audioHeader_ == null) {
              AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
            }
            input.ReadMessage(AudioHeader);
            break;
          }
          case 18: {
            if (faceParams_ == null) {
              FaceParams = new global::NvidiaAce.A2F.V1.FaceParameters();
            }
            input.ReadMessage(FaceParams);
            break;
          }
          case 26: {
            if (emotionPostProcessingParams_ == null) {
              EmotionPostProcessingParams = new global::NvidiaAce.A2F.V1.EmotionPostProcessingParameters();
            }
            input.ReadMessage(EmotionPostProcessingParams);
            break;
          }
          case 34: {
            if (blendshapeParams_ == null) {
              BlendshapeParams = new global::NvidiaAce.A2F.V1.BlendShapeParameters();
            }
            input.ReadMessage(BlendshapeParams);
            break;
          }
          case 42: {
            if (emotionParams_ == null) {
              EmotionParams = new global::NvidiaAce.A2F.V1.EmotionParameters();
            }
            input.ReadMessage(EmotionParams);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Event : pb::IMessage<Event>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Event> _parser = new pb::MessageParser<Event>(() => new Event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.Controller.V1.NvidiaAceControllerV1Reflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event(Event other) : this() {
      eventType_ = other.eventType_;
      metadata_ = other.metadata_ != null ? other.metadata_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Event Clone() {
      return new Event(this);
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 1;
    private global::NvidiaAce.Controller.V1.EventType eventType_ = global::NvidiaAce.Controller.V1.EventType.EndOfA2FAudioProcessing;
    /// <summary>
    /// Type of the event.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Controller.V1.EventType EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Any metadata_;
    /// <summary>
    /// Data attached to the event if any.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Metadata {
      get { return metadata_; }
      set {
        metadata_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventType != other.EventType) return false;
      if (!object.Equals(Metadata, other.Metadata)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventType != global::NvidiaAce.Controller.V1.EventType.EndOfA2FAudioProcessing) hash ^= EventType.GetHashCode();
      if (metadata_ != null) hash ^= Metadata.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventType != global::NvidiaAce.Controller.V1.EventType.EndOfA2FAudioProcessing) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (metadata_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Metadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventType != global::NvidiaAce.Controller.V1.EventType.EndOfA2FAudioProcessing) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (metadata_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Metadata);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventType != global::NvidiaAce.Controller.V1.EventType.EndOfA2FAudioProcessing) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      if (metadata_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Metadata);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Event other) {
      if (other == null) {
        return;
      }
      if (other.EventType != global::NvidiaAce.Controller.V1.EventType.EndOfA2FAudioProcessing) {
        EventType = other.EventType;
      }
      if (other.metadata_ != null) {
        if (metadata_ == null) {
          Metadata = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Metadata.MergeFrom(other.Metadata);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventType = (global::NvidiaAce.Controller.V1.EventType) input.ReadEnum();
            break;
          }
          case 18: {
            if (metadata_ == null) {
              Metadata = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Metadata);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventType = (global::NvidiaAce.Controller.V1.EventType) input.ReadEnum();
            break;
          }
          case 18: {
            if (metadata_ == null) {
              Metadata = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Metadata);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// IMPORTANT NOTE: this is an AnimationDataStreamHeader WITHOUT ID
  /// A similar AudioStreamHeader exist in nvidia_ace.animation_data.v1.proto
  /// but that one does contain IDs.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AnimationDataStreamHeader : pb::IMessage<AnimationDataStreamHeader>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnimationDataStreamHeader> _parser = new pb::MessageParser<AnimationDataStreamHeader>(() => new AnimationDataStreamHeader());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnimationDataStreamHeader> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.Controller.V1.NvidiaAceControllerV1Reflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationDataStreamHeader() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationDataStreamHeader(AnimationDataStreamHeader other) : this() {
      audioHeader_ = other.audioHeader_ != null ? other.audioHeader_.Clone() : null;
      skelAnimationHeader_ = other.skelAnimationHeader_ != null ? other.skelAnimationHeader_.Clone() : null;
      startTimeCodeSinceEpoch_ = other.startTimeCodeSinceEpoch_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationDataStreamHeader Clone() {
      return new AnimationDataStreamHeader(this);
    }

    /// <summary>Field number for the "audio_header" field.</summary>
    public const int AudioHeaderFieldNumber = 1;
    private global::NvidiaAce.Audio.V1.AudioHeader audioHeader_;
    /// <summary>
    /// Metadata of the audio buffers. This defines the audio clip properties
    /// at the beginning the streaming process.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Audio.V1.AudioHeader AudioHeader {
      get { return audioHeader_; }
      set {
        audioHeader_ = value;
      }
    }

    /// <summary>Field number for the "skel_animation_header" field.</summary>
    public const int SkelAnimationHeaderFieldNumber = 2;
    private global::NvidiaAce.AnimationData.V1.SkelAnimationHeader skelAnimationHeader_;
    /// <summary>
    /// Metadata containing the blendshape and joints names.
    /// This defines the names of the blendshapes and joints flowing through a stream.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.AnimationData.V1.SkelAnimationHeader SkelAnimationHeader {
      get { return skelAnimationHeader_; }
      set {
        skelAnimationHeader_ = value;
      }
    }

    /// <summary>Field number for the "start_time_code_since_epoch" field.</summary>
    public const int StartTimeCodeSinceEpochFieldNumber = 3;
    private double startTimeCodeSinceEpoch_;
    /// <summary>
    /// Time codes indicate the relative progression of an animation data, audio
    /// clip, etc. The unit is seconds. In addition, we also need an absolute time
    /// reference shared across services. The start time is stored in time codes
    /// elapsed since the Unix time epoch. start_time_code_since_epoch = `Unix
    /// timestamp in seconds`. NTP should be good enough to synchronize clocks
    /// across nodes. From Wikipedia: NTP can usually maintain time to within tens
    /// of milliseconds over the public Internet, and can achieve better than one
    /// millisecond accuracy in local area networks under ideal conditions.
    /// Alternatively, there is PTP.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StartTimeCodeSinceEpoch {
      get { return startTimeCodeSinceEpoch_; }
      set {
        startTimeCodeSinceEpoch_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnimationDataStreamHeader);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnimationDataStreamHeader other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AudioHeader, other.AudioHeader)) return false;
      if (!object.Equals(SkelAnimationHeader, other.SkelAnimationHeader)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StartTimeCodeSinceEpoch, other.StartTimeCodeSinceEpoch)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (audioHeader_ != null) hash ^= AudioHeader.GetHashCode();
      if (skelAnimationHeader_ != null) hash ^= SkelAnimationHeader.GetHashCode();
      if (StartTimeCodeSinceEpoch != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StartTimeCodeSinceEpoch);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (audioHeader_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AudioHeader);
      }
      if (skelAnimationHeader_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SkelAnimationHeader);
      }
      if (StartTimeCodeSinceEpoch != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(StartTimeCodeSinceEpoch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (audioHeader_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AudioHeader);
      }
      if (skelAnimationHeader_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(SkelAnimationHeader);
      }
      if (StartTimeCodeSinceEpoch != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(StartTimeCodeSinceEpoch);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (audioHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AudioHeader);
      }
      if (skelAnimationHeader_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SkelAnimationHeader);
      }
      if (StartTimeCodeSinceEpoch != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnimationDataStreamHeader other) {
      if (other == null) {
        return;
      }
      if (other.audioHeader_ != null) {
        if (audioHeader_ == null) {
          AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
        }
        AudioHeader.MergeFrom(other.AudioHeader);
      }
      if (other.skelAnimationHeader_ != null) {
        if (skelAnimationHeader_ == null) {
          SkelAnimationHeader = new global::NvidiaAce.AnimationData.V1.SkelAnimationHeader();
        }
        SkelAnimationHeader.MergeFrom(other.SkelAnimationHeader);
      }
      if (other.StartTimeCodeSinceEpoch != 0D) {
        StartTimeCodeSinceEpoch = other.StartTimeCodeSinceEpoch;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (audioHeader_ == null) {
              AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
            }
            input.ReadMessage(AudioHeader);
            break;
          }
          case 18: {
            if (skelAnimationHeader_ == null) {
              SkelAnimationHeader = new global::NvidiaAce.AnimationData.V1.SkelAnimationHeader();
            }
            input.ReadMessage(SkelAnimationHeader);
            break;
          }
          case 25: {
            StartTimeCodeSinceEpoch = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (audioHeader_ == null) {
              AudioHeader = new global::NvidiaAce.Audio.V1.AudioHeader();
            }
            input.ReadMessage(AudioHeader);
            break;
          }
          case 18: {
            if (skelAnimationHeader_ == null) {
              SkelAnimationHeader = new global::NvidiaAce.AnimationData.V1.SkelAnimationHeader();
            }
            input.ReadMessage(SkelAnimationHeader);
            break;
          }
          case 25: {
            StartTimeCodeSinceEpoch = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AnimationDataStream : pb::IMessage<AnimationDataStream>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AnimationDataStream> _parser = new pb::MessageParser<AnimationDataStream>(() => new AnimationDataStream());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AnimationDataStream> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NvidiaAce.Controller.V1.NvidiaAceControllerV1Reflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationDataStream() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationDataStream(AnimationDataStream other) : this() {
      switch (other.StreamPartCase) {
        case StreamPartOneofCase.AnimationDataStreamHeader:
          AnimationDataStreamHeader = other.AnimationDataStreamHeader.Clone();
          break;
        case StreamPartOneofCase.AnimationData:
          AnimationData = other.AnimationData.Clone();
          break;
        case StreamPartOneofCase.Event:
          Event = other.Event.Clone();
          break;
        case StreamPartOneofCase.Status:
          Status = other.Status.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AnimationDataStream Clone() {
      return new AnimationDataStream(this);
    }

    /// <summary>Field number for the "animation_data_stream_header" field.</summary>
    public const int AnimationDataStreamHeaderFieldNumber = 1;
    /// <summary>
    /// The header must be sent as the first message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Controller.V1.AnimationDataStreamHeader AnimationDataStreamHeader {
      get { return streamPartCase_ == StreamPartOneofCase.AnimationDataStreamHeader ? (global::NvidiaAce.Controller.V1.AnimationDataStreamHeader) streamPart_ : null; }
      set {
        streamPart_ = value;
        streamPartCase_ = value == null ? StreamPartOneofCase.None : StreamPartOneofCase.AnimationDataStreamHeader;
      }
    }

    /// <summary>Field number for the "animation_data" field.</summary>
    public const int AnimationDataFieldNumber = 2;
    /// <summary>
    /// Then one or more animation data message must be sent.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.AnimationData.V1.AnimationData AnimationData {
      get { return streamPartCase_ == StreamPartOneofCase.AnimationData ? (global::NvidiaAce.AnimationData.V1.AnimationData) streamPart_ : null; }
      set {
        streamPart_ = value;
        streamPartCase_ = value == null ? StreamPartOneofCase.None : StreamPartOneofCase.AnimationData;
      }
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 3;
    /// <summary>
    /// The event may be sent in between.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Controller.V1.Event Event {
      get { return streamPartCase_ == StreamPartOneofCase.Event ? (global::NvidiaAce.Controller.V1.Event) streamPart_ : null; }
      set {
        streamPart_ = value;
        streamPartCase_ = value == null ? StreamPartOneofCase.None : StreamPartOneofCase.Event;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 4;
    /// <summary>
    /// The status must be sent last and may be sent in between.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NvidiaAce.Status.V1.Status Status {
      get { return streamPartCase_ == StreamPartOneofCase.Status ? (global::NvidiaAce.Status.V1.Status) streamPart_ : null; }
      set {
        streamPart_ = value;
        streamPartCase_ = value == null ? StreamPartOneofCase.None : StreamPartOneofCase.Status;
      }
    }

    private object streamPart_;
    /// <summary>Enum of possible cases for the "stream_part" oneof.</summary>
    public enum StreamPartOneofCase {
      None = 0,
      AnimationDataStreamHeader = 1,
      AnimationData = 2,
      Event = 3,
      Status = 4,
    }
    private StreamPartOneofCase streamPartCase_ = StreamPartOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public StreamPartOneofCase StreamPartCase {
      get { return streamPartCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearStreamPart() {
      streamPartCase_ = StreamPartOneofCase.None;
      streamPart_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AnimationDataStream);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AnimationDataStream other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AnimationDataStreamHeader, other.AnimationDataStreamHeader)) return false;
      if (!object.Equals(AnimationData, other.AnimationData)) return false;
      if (!object.Equals(Event, other.Event)) return false;
      if (!object.Equals(Status, other.Status)) return false;
      if (StreamPartCase != other.StreamPartCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (streamPartCase_ == StreamPartOneofCase.AnimationDataStreamHeader) hash ^= AnimationDataStreamHeader.GetHashCode();
      if (streamPartCase_ == StreamPartOneofCase.AnimationData) hash ^= AnimationData.GetHashCode();
      if (streamPartCase_ == StreamPartOneofCase.Event) hash ^= Event.GetHashCode();
      if (streamPartCase_ == StreamPartOneofCase.Status) hash ^= Status.GetHashCode();
      hash ^= (int) streamPartCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (streamPartCase_ == StreamPartOneofCase.AnimationDataStreamHeader) {
        output.WriteRawTag(10);
        output.WriteMessage(AnimationDataStreamHeader);
      }
      if (streamPartCase_ == StreamPartOneofCase.AnimationData) {
        output.WriteRawTag(18);
        output.WriteMessage(AnimationData);
      }
      if (streamPartCase_ == StreamPartOneofCase.Event) {
        output.WriteRawTag(26);
        output.WriteMessage(Event);
      }
      if (streamPartCase_ == StreamPartOneofCase.Status) {
        output.WriteRawTag(34);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (streamPartCase_ == StreamPartOneofCase.AnimationDataStreamHeader) {
        output.WriteRawTag(10);
        output.WriteMessage(AnimationDataStreamHeader);
      }
      if (streamPartCase_ == StreamPartOneofCase.AnimationData) {
        output.WriteRawTag(18);
        output.WriteMessage(AnimationData);
      }
      if (streamPartCase_ == StreamPartOneofCase.Event) {
        output.WriteRawTag(26);
        output.WriteMessage(Event);
      }
      if (streamPartCase_ == StreamPartOneofCase.Status) {
        output.WriteRawTag(34);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (streamPartCase_ == StreamPartOneofCase.AnimationDataStreamHeader) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnimationDataStreamHeader);
      }
      if (streamPartCase_ == StreamPartOneofCase.AnimationData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnimationData);
      }
      if (streamPartCase_ == StreamPartOneofCase.Event) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Event);
      }
      if (streamPartCase_ == StreamPartOneofCase.Status) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AnimationDataStream other) {
      if (other == null) {
        return;
      }
      switch (other.StreamPartCase) {
        case StreamPartOneofCase.AnimationDataStreamHeader:
          if (AnimationDataStreamHeader == null) {
            AnimationDataStreamHeader = new global::NvidiaAce.Controller.V1.AnimationDataStreamHeader();
          }
          AnimationDataStreamHeader.MergeFrom(other.AnimationDataStreamHeader);
          break;
        case StreamPartOneofCase.AnimationData:
          if (AnimationData == null) {
            AnimationData = new global::NvidiaAce.AnimationData.V1.AnimationData();
          }
          AnimationData.MergeFrom(other.AnimationData);
          break;
        case StreamPartOneofCase.Event:
          if (Event == null) {
            Event = new global::NvidiaAce.Controller.V1.Event();
          }
          Event.MergeFrom(other.Event);
          break;
        case StreamPartOneofCase.Status:
          if (Status == null) {
            Status = new global::NvidiaAce.Status.V1.Status();
          }
          Status.MergeFrom(other.Status);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::NvidiaAce.Controller.V1.AnimationDataStreamHeader subBuilder = new global::NvidiaAce.Controller.V1.AnimationDataStreamHeader();
            if (streamPartCase_ == StreamPartOneofCase.AnimationDataStreamHeader) {
              subBuilder.MergeFrom(AnimationDataStreamHeader);
            }
            input.ReadMessage(subBuilder);
            AnimationDataStreamHeader = subBuilder;
            break;
          }
          case 18: {
            global::NvidiaAce.AnimationData.V1.AnimationData subBuilder = new global::NvidiaAce.AnimationData.V1.AnimationData();
            if (streamPartCase_ == StreamPartOneofCase.AnimationData) {
              subBuilder.MergeFrom(AnimationData);
            }
            input.ReadMessage(subBuilder);
            AnimationData = subBuilder;
            break;
          }
          case 26: {
            global::NvidiaAce.Controller.V1.Event subBuilder = new global::NvidiaAce.Controller.V1.Event();
            if (streamPartCase_ == StreamPartOneofCase.Event) {
              subBuilder.MergeFrom(Event);
            }
            input.ReadMessage(subBuilder);
            Event = subBuilder;
            break;
          }
          case 34: {
            global::NvidiaAce.Status.V1.Status subBuilder = new global::NvidiaAce.Status.V1.Status();
            if (streamPartCase_ == StreamPartOneofCase.Status) {
              subBuilder.MergeFrom(Status);
            }
            input.ReadMessage(subBuilder);
            Status = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::NvidiaAce.Controller.V1.AnimationDataStreamHeader subBuilder = new global::NvidiaAce.Controller.V1.AnimationDataStreamHeader();
            if (streamPartCase_ == StreamPartOneofCase.AnimationDataStreamHeader) {
              subBuilder.MergeFrom(AnimationDataStreamHeader);
            }
            input.ReadMessage(subBuilder);
            AnimationDataStreamHeader = subBuilder;
            break;
          }
          case 18: {
            global::NvidiaAce.AnimationData.V1.AnimationData subBuilder = new global::NvidiaAce.AnimationData.V1.AnimationData();
            if (streamPartCase_ == StreamPartOneofCase.AnimationData) {
              subBuilder.MergeFrom(AnimationData);
            }
            input.ReadMessage(subBuilder);
            AnimationData = subBuilder;
            break;
          }
          case 26: {
            global::NvidiaAce.Controller.V1.Event subBuilder = new global::NvidiaAce.Controller.V1.Event();
            if (streamPartCase_ == StreamPartOneofCase.Event) {
              subBuilder.MergeFrom(Event);
            }
            input.ReadMessage(subBuilder);
            Event = subBuilder;
            break;
          }
          case 34: {
            global::NvidiaAce.Status.V1.Status subBuilder = new global::NvidiaAce.Status.V1.Status();
            if (streamPartCase_ == StreamPartOneofCase.Status) {
              subBuilder.MergeFrom(Status);
            }
            input.ReadMessage(subBuilder);
            Status = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
